from flask import Flask, request, render_template, redirect, url_for, send_file
import tensorflow as tf
import numpy as np
import os
from gtts import gTTS

app = Flask(__name__)

# Load the trained model
model_path = r'D:\Detection\model\model_avg.h5'
model = tf.keras.models.load_model(model_path)

# Labels and plant information
labels = {
    0: 'Aloevera', 1: 'Amla', 2: 'Amruta_Balli', 3: 'Arali', 4: 'Ashoka', 5: 'Ashwagandha', 6: 'Avacado', 7: 'Bamboo', 8: 'Basale', 9: 'Betel', 10: 'Betel_Nut',
    11: 'Brahmi', 12: 'Castor', 13: 'Curry_Leaf', 14: 'Doddapatre', 15: 'Ekka', 16: 'Ganike',
    17: 'Gauva', 18: 'Geranium', 19: 'Henna', 20: 'Hibiscus', 21: 'Honge', 22: 'Insulin',
    23: 'Jasmine', 24: 'Lemon', 25: 'Lemon_grass', 26: 'Mango', 27: 'Mint', 28: 'Nagadali',
    29: 'Neem', 30: 'Nithyapushpa', 31: 'Nooni', 32: 'Pappaya', 33: 'Pepper', 34: 'Pomegranate',
    35: 'Raktachandini', 36: 'Rose', 37: 'Sapota', 38: 'Tulasi', 39: 'Wood_sorel'
}

# Plant information dictionary
plant_desc = {
    'Aloevera': 'Aloevera is a succulent plant species of the genus Aloe. It is widely distributed, and is considered an invasive species in many world regions. An evergreen perennial, it originates from the Arabian Peninsula, but also grows wild in tropical, semi-tropical, and arid climates around the world. It is cultivated for commercial products, mainly as a topical treatment used over centuries. The species is considered attractive for decorative purposes, and is often used indoors as a potted plant. The leaves of Aloe vera contain significant amounts of the polysaccharide gel acemannan, which can be used for topical purposes. Aloe skin contains aloin which is toxic. Products made from Aloe vera usually only use the gel.There are many products containing aloe veras acemannan, including skin lotions, cosmetics, ointments and gels for minor burns, skin abrasions, insect bites, and windburn. Oral ingestion of aloe vera extracts can be dangerous, because it causes reactions which are not yet fully understood. It is especially dangerous for pregnant women. Some people have allergic reactions, even when the aloe vera is applied only to the skin.',
    'Amla': 'Amla is a deciduous tree of the family Phyllanthaceae. It has edible fruit, referred to by the same name. Indian gooseberry is a tree that grows in India, the Middle East, and some southeast Asian countries. Indian gooseberry has been used in Ayurvedic medicine for thousands of years. Today people still use the fruit of the tree to make medicine. Amla fruits are a very rich source of vitamin C having an ascorbic acid content varying from 0.9% to 1.3%, the second highest among all the fruits cultivated. Vitamin C rich amla can give a boost to your immunity. Vitamin C is important for children, adults, and the elderly. Free radicals in the body can damage heart, skin and even hampers our immunity.',
    'Amruta_Balli': 'Amrutha Balli, also known as Giloy or Tinospora Cordifolia, is a powerful medicinal herb widely used in Ayurvedic practices for its numerous health benefits. This hearty green climber is known for its ability to boost immunity, detoxify the body, and promote overall well-being. Traditionally used to manage fevers, infections, and digestive issues, Amrutha Balli is a versatile addition to your diet. Leaves simple heart shaped, very thin with long leaf stalks bulged at the base and apex and  arranged alternately. Inflorescence, called racemes are both  axillary and terminal; flowers tiny, greenish yellow, unisexual with male and female flowers on separate plants; stamens 6; female flowers with staminodes and carpels. Fruits  are called drupelets (1-3); ovoid  and scarlet coloured when ripe.',
    'Arali': 'Arali commonly known as oleander or rosebay, is a shrub or small tree cultivated worldwide in temperate and subtropical areas as an ornamental and landscaping plant. It is the only species currently classified in the genus Nerium, belonging to subfamily Apocynoideae of the dogbane family Apocynaceae. It is so widely cultivated that no precise region of origin has been identified, though it is usually associated with the Mediterranean Basin. Oleander is a very poisonous plant, containing a powerful cardiac toxin and should only be used with extreme caution. The leaves and the flowers are cardiotonic, diaphoretic, diuretic, emetic, expectorant and sternutatory. A decoction of the leaves has been applied externally in the treatment of scabies and parasitic skin worms. An oil prepared from the root bark is used in the treatment of leprosy and skin diseases of a scaly nature. The plant is used as a rat poison.',
    'Ashoka': 'The Ashoka tree or Saraca indica, has been revered in the traditional Ayurvedic medicine for centuries. This is because this miraculous plant holds a treasure trove of therapeutic potential and health advantages, making it a valuable addition to your health arsenal. What’s more, this versatile ingredient can be used in a variety of ways like Ashoka churna, Ashoka powder and Ashoka capsules. Keep reading to learn more Ashoka tree benefits and uses to open new avenues for holistic wellness. The leaves of the Ashoka plant contain several bioactive compounds such as steroids, proteins, carbohydrates, flavonoids, tannins and glycosides.',
    'Ashwagandha': 'Ashwagandha is an evergreen shrub that grows in Asia and Africa. It is commonly used for stress. There is little evidence for its use as an "adaptogen." Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system. Since ashwagandha is traditionally used as an daptogen, it is used for many conditions related to stress. Adaptogens are believed to help the body resist physical and mental stress. Some of the conditions it is used for include insomnia, aging, anxiety and many others, but there is no good scientific evidence to support most of these uses. ',
    'Avacado' : 'Avocado, (Persea americana), tree of the family Lauraceae and its edible fruit. Avocados are native to the Western Hemisphere from Mexico south to the Andean regions and are widely grown in warm climates. Avocado fruits have greenish or yellowish flesh with a buttery consistency and a rich nutty flavour. They are often eaten in salads, and in many parts of the world they are eaten as a dessert. Mashed avocado is the principal ingredient of guacamole, a characteristic saucelike condiment in Mexican cuisine. Avocados provide thiamin, riboflavin, and vitamin A, and in some varieties the flesh contains as much as 25 percent unsaturated oil. Avocado trees can be tall or spreading, and they have elliptic to egg-shaped leaves that are 10–30 cm (4–12 inches) in length. The small greenish flowers are borne in dense inflorescences and lack true petals. The flowers have nine stamens, arranged in three series, and a one-celled ovary. Interestingly, there are two types of avocado flowers, A and B, depending on the cultivar. ',
    'Bamboo' : 'The Bamboos (Bambusoidaea) consists of 1439 different species in 116 genera. It is one of the 12 subfamilies of the grass family (Poaceae) and the only one to diversify in forests. Bamboo is a great plant for individuals concern with a green environment. Bamboo is the fastest growing plant on this planet. It has been recorded growing at an amazing 47.6 inches in a 24 hour period. Bamboo is a crucial element in the balance of oxygen and carbon dioxide in the atmosphere.  A grove of bamboo release 35% more oxygen than an equivalent stand of trees. Because of this, planting bamboo is a great way to reduce your carbon footprint and help fight global warming. Bamboo is a viable replacement for wood. It can be harvest in 3-5 years versus 10-20 for most softwoods. It can out yield pine 6 to 1 in biomass production. It is also one of the strongest building materials with a tensile strength of 28,000 psi. To help give you an idea how much this is, mild steel measures 23,000 psi. It is a great soil conservation tool. It greatly reduces erosion with a sum of stem flow rate and canopy intercept of 25%. This dramatically reduces rain run-off, preventing massive soil erosion and making it very earth friendly.',
    'Basale' : 'Basale soppu goes by many names. It’s often called Mangalore spinach or vine spinach or, in the US, on the rare occasion when you can find it in non-Indian stores, it’s generally sold as Malabar spinach, after the stretch of coast on the West side of India that includes Kerala. In India, though, its names are even more numerous and diverse: in Gujarati it’s called poi ni bhaji, in Telugu it’s known as bacchali, and in Konkani it’s called vauchi bhaji. Whatever you call it, though, the greens have a distinctive taste and texture, and elicit either wild fandom or loathing. The Latin name, curiously enough, mirrors the Kannada name quite closely: Basella alba (a green-stemmed variety) and Basella rubra (red-stemmed) are the two sorts of this green that you’re likely to find if you go looking for it. The plants love heat and humidity, and flourish in the humid low-lying coastal areas of southwestern India. But there’s no reason why they couldn’t do well in the Northeast for at least part of the year. They grow rampant in kitchen gardens throughout the south of India, and because they love to climb once the summer heat kicks in, it’s not uncommon to see them twisting around stakes in the ground and drawn out between a post and a nearby coconut tree.',
    'Betel' : 'The betel vine (Piper betle L.) is a perennial climber belonging to the family Piperaceae. Betelvine has been widely used in various parts of India and other South Asian countries for centuries. The name Piper is probably originated from the Sanskrit term ‘Pippali’ (meaning long pepper) and the name ‘betle’ might have come from the Malayalam word ‘Vetila’. It is cultivated, as a commercial crop, for its leaf, which is used as a masticatory. As a masticatory, the betel leaf (pan) is credited with aromatic, digestive, stimulant and carminative properties. Betel chewing imparts a pleasant odour to the oral cavity and also warmth and a feeling of well-being. Hydrated lime is spread over the betel leaf and is chewed with a few pieces of arecanut (Areca catechu). Other spices and masticatories such as cardamom, fennel, nutmeg, clove and tobacco are also added to the betel (leaf roll) quid preparation. Betel chewing is prevalent in all south Asian countries, Indonesia, many Pacific Ocean Islands and Middle East and South-East Asia.',
    'Betel_Nut': 'The areca nut  or betel nut is the fruit of the areca palm (Areca catechu). The palm is originally native to the Philippines, but was carried widely through the tropics by the Austronesian migrations and trade since at least 1500 BCE due to its use in betel nut chewing. It is widespread in cultivation and is considered naturalized in much of the tropical Pacific (Melanesia and Micronesia), South Asia, Southeast Asia, and parts of east Africa. It is not to be confused with betel (Piper betle) leaves that are often used to wrap it. The practice of betel nut chewing, often together with other herbs as a stimulant drug, dates back thousands of years, and continues to the present day in many countries. Betel nut chewing is addictive due to the presence of the stimulant arecoline, and causes adverse health effects, mainly oral and esophageal cancers, and cardiovascular disease. When chewed with additional tobacco in its preparation (like in gutka), there is an even higher risk, especially for oral and oropharyngeal cancers. With tobacco it also raises the risk of fatal coronary artery disease, fatal stroke, and adverse reproductive effects including stillbirth, premature birth, low birth weight.',
    'Brahmi' : 'Brahmi is found in humid and warmer parts of the world. It is a common creeping annual growing in damp and marshy areas. The whole plant is used in indigenous system of medicine as a nerve tonic and for epilepsy and insanity. It is also being used as diuretic and for treating rheumatisim, asthma and hoarseness. Besides, brahmi also has good potency in controlling cough, fever and diabetes. Because of its inherent potential of enhancing memory and vitality, this miracle plant is gaining attention for its commercial cultivation globally. This plant is considered among one of the ‘celestrial drugs’ (Divya ausadhi), when consumed with milk for six months. In siddha system of medicine, the plant is useful against painful joints, swelling in joints, peripheral neuritis, constipation and burning urination. It is also used in convulsions, mental retardation, chest congestion and laryngitis.',
    'Castor' : 'Castor-oil plant, (Ricinus communis), large plant of the spurge family (Euphorbiaceae), grown commercially for the pharmaceutical and industrial uses of its oil and for use in landscaping. Probably native to tropical Africa, the castor-oil plant has become naturalized throughout warm areas of the world. The plants are chiefly cultivated in India, China, and Brazil, largely as the source of castor oil. Although the plant is the only species in its genus, there are hundreds of natural forms and many horticultural varieties. The oil-rich seeds contain the poison ricin, one of the most toxic substances known, and consumption of chewed seeds can be lethal. Castor-oil plant 1 of 2 castor-oil plantFruits of the castor-oil plant, or castor bean (Ricinus communis). Castor bean seeds 2 of 2 castor bean seedsCastor bean seeds used to make oil cakes. In the tropics the plants reach about 10 to 13 metres (30 to 40 feet) in height. In temperate climates they are raised as annuals and grow 1.5 to 2.5 metres (4.9 to 8 feet) in a single season. The plants bear handsome giant 12-lobed palmate (fanlike) leaves. The bristly spined bronze-to-red clusters of fruits are attractive but often are removed before they mature, because of the ricin concentrated in their mottled beanlike seeds.',
    'Curry_Leaf' : 'The curry tree or Bergera koenigii (syn. Murraya koenigii), is a tropical and sub-tropical tree in the family Rutaceae (the rue family, which includes rue, citrus, and satinwood), native to Asia. The plant is also sometimes called sweet neem, though M. koenigii is in a different family from neem, Azadirachta indica, which is in the related family Meliaceae. Its leaves, known as curry leaves, also referred to as sweet neem, are used in many dishes in the Indian subcontinent. It is a small tree, growing 4–6 metres (13–20 ft)) tall, with a trunk up to 40 cm (16 in) in diameter. The aromatic leaves are pinnate, with 11–21 leaflets, each leaflet 2–4 cm (3⁄4–1+1⁄2 in) long and 1–2 cm (1⁄2–3⁄4 in) broad. The plant produces small white flowers which can self-pollinate to produce small shiny-black drupes containing a single, large viable seed. The berry pulp is edible, with a sweet flavor.',
    'Doddapatre' : ' Doddapatre is a known indian medicinal plant with lots of health benefits. It is every household plant in india. parents, grandparents used this doddapatre leaves as medicine and as greens to prepare delicious recipes. This is also called Indian borage, mexican mint, country borage. We can easily grow doddapatre in small pots. It grows well in full sunlight and also in partial shade as well. Doddapatre plants are usually propagated by stem cuttings and are a low maintenance plant. I suggest/ recommend everyone to have this plant at home. a good source of vitamins and minerals, including vitamin C, calcium, and iron. It also contains antioxidants, such as rosmarinic acid, which has been shown to have anti-inflammatory properties and protect against chronic diseases, such as heart disease and cancer.',
    'Ekka' : 'Ekka, the crown flower, is a species of Calotropis native to Cambodia, Vietnam, Bangladesh, Indonesia, Malaysia, Thailand, Sri Lanka, India, China, Pakistan, and Nepal. It is a large shrub growing to 4 m (13 ft) tall. It has clusters of waxy flowers that are either white or lavender in colour. Each flower consists of five pointed petals and a small "crown" rising from the center which holds the stamens. The aestivation found in calotropis is valvate i.e. sepals or petals in a whorl just touch one another at the margin, without overlapping. The plant has oval, light green leaves and milky stem. The latex of Calotropis gigantea contains cardiac glycosides, fatty acids, and calcium oxalate. The roots also contain Calotropone.',
    'Ganike' : 'The Ganike plant, also known as Solanum nigrum or black nightshade. Solanum nigrum, the European black nightshade or simply black nightshade or blackberry nightshade, is a species of flowering plant in the family Solanaceae, native to Eurasia and introduced in the Americas, Australasia, and South Africa. Ripe berries and cooked leaves of edible strains are used as food in some locales, and plant parts are used as a traditional medicine. Some other species may also be referred to as "black nightshade". Solanum nigrum has been recorded from deposits of the Paleolithic and Mesolithic era of ancient Britain and it is suggested by the botanist and ecologist Edward Salisbury that it was part of the native flora there before Neolithic agriculture emerged. The species was mentioned by Pliny the Elder in the first century AD and by the great herbalists, including Dioscorides. In 1753, Carl Linnaeus described six varieties of Solanum nigrum in Species Plantarum.',
    'Gauva' : 'Guava is a common tropical fruit cultivated in many tropical and subtropical regions. The common guava Psidium guajava (lemon guava, apple guava) is a small tree in the myrtle family (Myrtaceae), native to Mexico, Central America, the Caribbean and northern South America. The name guava is also given to some other species in the genus Psidium such as strawberry guava (Psidium cattleyanum) and to the pineapple guava, Feijoa sellowiana. In 2019, 55 million tonnes of guavas were produced worldwide, led by India with 45% of the total. Botanically, guavas are berries. Guava fruits, usually 4 to 12 centimetres (1+1⁄2 to 4+1⁄2 in) long, are round or oval depending on the species. They have a pronounced and typical fragrance, similar to lemon rind but less sharp. The outer skin may be rough, often with a bitter taste, or soft and sweet. Varying between species, the skin can be any thickness, is usually green before maturity, but may be yellow, maroon, or green when ripe. The pulp inside may be sweet or sour and off-white ("white" guavas) to deep pink ("red" guavas). The seeds in the central pulp vary in number and hardness, depending on species.',
    'Geranium' : 'Geranium is a genus of 422 species of annual, biennial, and perennial plants that are commonly known as geraniums or cranesbills. They are found throughout the temperate regions of the world and the mountains of the tropics, with the greatest diversity in the eastern part of the Mediterranean region. The palmately cleft leaves are broadly circular in form. The flowers have five petals and are coloured white, pink, purple, or blue, often with distinctive veining. Geraniums will grow in any soil as long as it is not waterlogged. Propagation is by semiripe cuttings in summer, by seed, or by division in autumn or spring. Geraniums are eaten by the larvae of some Lepidoptera species including brown-tail, ghost moth, and mouse moth. At least several species of Geranium are gynodioecious. The species Geranium viscosissimum (sticky geranium) is considered to be protocarnivorous.',
    'Henna' : 'Henna is a reddish dye prepared from the dried and powdered leaves of the henna tree. It has been used since at least the ancient Egyptian period as a hair and body dye, notably in the temporary body art of mehndi (or "henna tattoo") resulting from the staining of the skin using dyes from the henna plant. After henna stains reach their peak colour, they hold for a few days, then gradually wear off by way of exfoliation, typically within one to three weeks. Henna has been used in ancient Egypt, ancient Near East and then the Indian subcontinent to dye skin, hair and fingernails, as well as fabrics including silk, wool, and leather. Historically, henna was used in West Asia including the Arabian Peninsula and in Carthage, other parts of North Africa, West Africa, Central Africa, the Horn of Africa and the Indian subcontinent. The name henna is used in other skin and hair dyes, such as black henna and neutral henna, neither of which is derived from the henna plant.',
    'Hibiscus' : 'Hibiscus is a flowering plant that belongs to the family Malvaceae, also known as mallow family. The Hibiscus flowers are large and showy, and the genus grows into herbs, shrubs or small trees. There are more than hundred species found that are used throughout the world as food and medicine. Tea made with Hibiscus flowers is served as both cold and hot beverages in many countries. The beverage is full of flavour, tangy and coloured. The seed is full of proteins and antioxidants and is consumed after meals or as an alternative to coffee. The oil extracted from Hibiscus seeds is used in cooking. The extracts of Hibiscus have antihypertensive, antioxidant, antifungal, antibacterial and antipyretic properties but need more scientific backing.',
    'Honge' : 'Honge is a species of tree in the pea family, Fabaceae, native to eastern and tropical Asia, Australia, and the Pacific islands. It is the sole species in genus Pongamia. It is often known by the synonym Millettia pinnata. Its common names include Indian beech, Karanja, and Pongame oiltree. Pongamia pinnata is well-adapted to arid zones, and has many traditional uses. It is often used for landscaping as a windbreak or for shade due to the large canopy and showy, fragrant flowers. The flowers are used by gardeners as compost for plants. The bark may be used to make twine or rope, and it also yields a black gum that has historically been used to treat wounds caused by poisonous fish. The wood is said to be beautifully grained, but splits easily when sawn, thus relegating it to firewood, posts, and tool handles. The trees deep taproot and drought tolerance makes this tree ideal for controlling soil erosion and binding sand dunes.',
    'Insulin' : 'Costus igneus is known as the insulin plant because it may help lower glucose levels for some people with diabetes. This plant may cause side effects that include dizziness and stomach problems. While C. igneus may help as a supplement for pre-diabetes or type 2 diabetes, it is not a replacement for insulin or other diabetes medications. Costus igneus is an herbal plant from Central and South America that’s more commonly known as the insulin plant. Researchers believe it can help lower blood sugar levels in certain people with diabetes. While it may have some anti-diabetic properties that could be beneficial if used as a supplement, this floral plant can also lead to side effects like dizziness, diarrhea, nausea — even dangerously low blood sugars if it interacts with your other diabetes medications. This article will provide more information about this particular plant and whether it might be worth considering as an option for diabetes management, including information about possible side effects and how it can impact glucose levels. Importantly, you should consult your doctor or healthcare team before making any decisions on using the insulin plant or making any changes to your current diabetes care plan.',
    'Jasmine' : 'Jasmine is a genus of shrubs and vines in the olive family of Oleaceae. It contains around 200 species native to tropical and warm temperate regions of Eurasia, Africa, and Oceania. Jasmines are widely cultivated for the characteristic fragrance of their flowers. The flowers are typically around 2.5 cm (0.98 in) in diameter. They are white or yellow, although in rare instances they can be slightly reddish. The flowers are borne in cymose clusters with a minimum of three flowers, though they can also be solitary on the ends of branchlets. Each flower has about four to nine petals, two locules, and one to four ovules. They have two stamens with very short filaments. The bracts are linear or ovate. The calyx is bell-shaped. They are usually very fragrant.',
    'Lemon' : 'The lemon (Citrus × limon) is a species of small evergreen tree in the Citrus genus of the flowering plant family Rutaceae, native to Asia, including Northeast India where it was first grown. It is a hybrid of the citron and the bitter orange. The trees yellow fruit is used throughout the world, primarily for its juice. The pulp and rind are used in cooking and baking. The juice of the lemon is about 5–6% citric acid, giving it a sour taste. This makes it a key ingredient in drinks and foods such as lemonade and lemon meringue pie. The fruits have appeared in art since the time of ancient Egypt. In 2022, world production was 22 million tonnes, led by India with 18% of the total. Lemon is a rich source of vitamin C, providing 64% of the Daily Value in a 100 g reference amount (table). Other essential nutrients are low in content. ',
    'Lemon_grass' : 'Lemongrass, Cymbopogon citratus, is a perennial grass in the family Poaceae grown for its fragrant leaves and stalks which are used as a flavoring. The grass grows in dense clumps and has several stiff stems and slender blade-like leaves which droop towards the tips. The leaves are blue-green in color, turning red in the Fall and emit a strong lemon fragrance when damaged. Lemongrass produces large compound flowers on spikes when grown in the tropics, but rarely flowers when grown in more Northern latitudes. Lemon grass can reach a height of 1.8 m (6 ft) and will grow for several years, typically its economical lifespan is 4 years. Lemongrass may also be referred to as ginger grass or citronella grass and likely originates from Sri Lanka or Malaysia although a wild form of the plant is not known. The stalks (leaf bases) of the plant are commonly used to flavor dishes in Southeast Asian cooking. The heart of young shoots may be cooked and consumed as a vegetable. The tougher leaves are used to flavor dishes but are typically removed before serving. Leaves may also be used to make lemon grass tea. The essential oil extracted from the leaves is commonly used in insect repellents, perfumes and soaps.',
    'Mango' : 'Mangifera indica, commonly known as mango, is an evergreen species of flowering plant in the family Anacardiaceae. It is a large fruit tree, capable of growing to a height and width of 30 metres (100 feet)[1]. There are two distinct genetic populations in modern mangoes – the "Indian type" and the "Southeast Asian type". Mangifera indica is a large green tree, valued mainly for its fruits, both green and ripe. Approximately 500 (with more than 1000 wild which are unreported as each monoembryonic seed gives a new variety of mango) varieties have been reported in India. It can grow up to 15–30 metres (50–100 feet) tall with a similar crown width and a trunk circumference of more than 3.7 m (12 ft). The leaves are simple, shiny and dark green. The tree is more known for its fruit rather than for its timber. However, mango trees can be converted to lumber once their fruit-bearing lifespan has finished. The wood is susceptible to damage from fungi and insects. The wood is used for musical instruments such as ukuleles, plywood and low-cost furniture.',
    'Mint' : 'Mint or mentha belongs to the Lamiaceae family, which contains around 15–20 plant species, including peppermint and spearmint. It is a popular herb that people can use fresh or dried in many dishes and infusions. Manufacturers of toothpaste, gum, candy, and beauty products often use mint oil. Using fresh mint and other herbs and spices in cooking can help a person add flavor while reducing their sodium and sugar intake. Throughout history, people have used different species of mint plants in medicine. Different types of mint plants offer a range of antioxidant qualities and potential health benefits, especially for people who have irritable bowel syndrome (IBS). In this article, we provide a nutritional breakdown of mint and explain its possible health benefits. We also give tips on including more mint in the diet.',
    'Nagadali' : 'Nagadali commonly known as rue, common rue or herb-of-grace, is a species of Ruta grown as an ornamental plant and herb. It is native to the Balkan Peninsula. It is now grown throughout the world in gardens, especially for its bluish leaves, and sometimes for its tolerance of hot and dry soil conditions. It is also cultivated as a medicinal herb, as a condiment, and to a lesser extent as an insect repellent. Rue has a culinary use, but since it is bitter and gastric discomfort may be experienced by some individuals, it is used sparingly. Although used more extensively in former times, it is not a herb that is typically found in modern cuisine. Today it is largely unknown to the general public and most chefs, and unavailable in grocery stores. It is a component of berbere, the characteristic Ethiopian spice mixture, and as such is encountered in Ethiopian cuisine. Also in Ethiopia, fresh rue is dipped in coffee before drinking it. It was used extensively in ancient Near Eastern and Roman cuisine (according to Ibn Sayyar al-Warraq and Apicius). Rue is used as a traditional flavouring in Greece and other Mediterranean countries.',
    'Neem' : 'Neem, (Azadirachta indica), fast-growing tree of the mahogany family (Meliaceae), valued as a medicinal plant, as a source of organic pesticides, and for its timber. Neem is likely native to the Indian subcontinent and to dry areas throughout South Asia. It has been introduced to parts of Africa, the Caribbean, and numerous counties in South and Central America. The plant has long been used in Ayurvedic and folk medicine and is used in cosmetics and in organic farming applications. Neem trees can reach 15–30 metres (49–98 feet) in height and have attractive rounded crowns and thick furrowed bark. The compound leaves have toothed leaflets and are typically evergreen but do drop during periods of extreme drought. The small fragrant white flowers are bisexual or staminate (male) and are borne in clusters in the axils of the leaves. The fruit is a smooth yellow-green drupe and has a sweet-flavoured pulp. Neem is usually grown from seed but can be propagated from cuttings or root suckers. The plant is hardy and resilient and grows well in poor, rocky soils. Neem tolerates a wide variety of environmental conditions but cannot survive freezing temperatures or being waterlogged.', 
    'Nithyapushpa' : 'Nithyapushpa commonly known as Catharanthus. Catharanthus is a genus of flowering plants in the family Apocynaceae. Like the genus Vinca, they are known commonly as periwinkles. There are eight known species. Seven are endemic to Madagascar, though one, C. roseus, is widely naturalized around the world. The eighth species, C. pusillus, is native to India and Sri Lanka. The name Catharanthus comes from the Greek for "pure flower". These are perennial herbs with oppositely or almost oppositely arranged leaves. Flowers are usually solitary in the leaf axils. Each has a calyx with five long, narrow lobes and a corolla with a tubular throat and five lobes. Catharanthus roseus, known formerly as Vinca rosea, is a main source of vinca alkaloids, now sometimes called catharanthus alkaloids. The plant produces about 130 of these compounds, including vinblastine and vincristine, two drugs used to treat cancer. Catharanthus roseus is also cultivated as an ornamental plant in gardens. Several cultivars have been bred to produce flowers in many shades of pink, red, lilac, and white, or in light shades with dark throats.',
    'Nooni' : 'The noni plant, native to Asia, Australia, and the islands of Polynesia, is a small, shrubby tree. The plants white flowers are tubular. The fruit is yellow-greenish-white in color and large, with a pebbled surface. The ripe fruit has a characteristic cheese-like, bad odor. Noni is also known as morinda, ach, achi, anino, awltree, bengkudu, bo-aal, caribe te, dilo-K, hag apple, hog apple, ice leaf, Indian mulberry, kura. Polynesian healers have used noni fruits for thousands of years to help treat a variety of health problems such as diabetes, high blood pressure, aches, pains, burns, arthritis, inflammation, tumors, the effects of aging, and parasitic, viral, and bacterial infections. Ancient healing manuscripts cite the fruit as a primary ingredient in natural healing formulations. Today, fruit preparations are sold as juice, in dried "fruit-leather" form, and as a dry extract in capsules. Noni has traditionally been used for colds, flu, diabetes, anxiety, and high blood pressure, as well as for depression and anxiety. All plant parts are used for a variety of illnesses in Samoan culture, and noni is one of the most frequently used Hawaiian plant medicines. Claims that have not been proven in clinical trials include: the use of bark for the treatment of bacterial infections, cough, diarrhea in infants, and stomach ailments; the flowers for sore or irritated eyes, styes, conjunctivitis, ocular inflammation, and coughs; the fruit for asthma, wounds, broken bones, mouth and throat infections.',
    'Pappaya' : 'Papaya, (Carica papaya), succulent fruit of a large plant of the family Caricaceae. Though its origin is rather obscure, the papaya may represent the fusion of two or more species of Carica native to Mexico and Central America. Today it is cultivated throughout the tropical world and into the warmest parts of the subtropics. The papaya fruit is slightly sweet, with an agreeable musky tang, which is more pronounced in some varieties and in some climates than in others. It is a popular breakfast fruit in many countries and is also used in salads, pies, sherbets, juices, and confections. The unripe fruit can be cooked like squash. The papaya plant is considered a tree, though its palmlike trunk, up to 8 metres (26 feet) tall, is not as woody as the designation generally implies. The plant is crowned by deeply lobed leaves, sometimes 60 cm (2 feet) across, borne on hollow petioles (leaf stalks) 60 cm long. Normally, the species is dioecious, male and female flowers being produced on separate plants, but hermaphroditic forms are known, and numerous irregularities in the distribution of the sexes are common. Male flowers are borne in clusters on stalks 90 cm long; the flowers are funnel-shaped, about 2.5 mm (0.1 inch) long, and whitish, with 10 stamens in the throat. The female flowers are considerably larger, on very short stalks, and often solitary in the leaf axils; they have five fleshy petals that are united toward the base and a large cylindrical or globose superior ovary that is crowned by five fan-shaped sessile stigmas. The fruit is commonly spherical to cylindrical in form, is 75 to 500 mm (3 to 20 inches) or even more in length, and sometimes weighs as much as 9 to 11.5 kg (20 to 25.5 pounds). The very juicy flesh is deep yellow or orange to salmon-coloured. Along the walls of the large central cavity are attached the numerous round, wrinkled black seeds.',
    'Pepper' : 'Black pepper (Piper nigrum) is a flowering vine in the family Piperaceae, cultivated for its fruit (the peppercorn), which is usually dried and used as a spice and seasoning. The fruit is a drupe (stonefruit) which is about 5 mm (0.20 in) in diameter (fresh and fully mature), dark red, and contains a stone which encloses a single pepper seed. Peppercorns and the ground pepper derived from them may be described simply as pepper, or more precisely as black pepper (cooked and dried unripe fruit), green pepper (dried unripe fruit), or white pepper (ripe fruit seeds). Black pepper is native to the Malabar Coast of India, and the Malabar pepper is extensively cultivated there and in other tropical regions. Ground, dried, and cooked peppercorns have been used since antiquity, both for flavour and as a traditional medicine. Black pepper is the worlds most traded spice, and is one of the most common spices added to cuisines around the world. Its spiciness is due to the chemical compound piperine, which is a different kind of spiciness from that of capsaicin characteristic of chili peppers. It is ubiquitous in the Western world as a seasoning, and is often paired with salt and available on dining tables in shakers or mills.',
    'Pomegranate' : 'The pomegranate (Punica granatum) is a fruit-bearing deciduous shrub in the family Lythraceae, subfamily Punicoideae, that grows between 5 and 10 m (16 and 33 ft) tall. The pomegranate is rich in symbolic and mythological associations in many cultures. The pomegranate is thought to have originated from Afghanistan and Iran before being introduced and exported to other parts of Asia, Africa, and Europe. It was introduced into Spanish America in the late 16th century and into California by Spanish settlers in 1769. It is widely cultivated throughout West Asia and Caucasus region, South Asia, Central Asia, north and tropical Africa, the drier parts of Southeast Asia, and the Mediterranean Basin. The fruit is typically in season in the Southern Hemisphere from March to May, and in the Northern Hemisphere from September to February. Pomegranate and juice are variously used in baking, cooking, juice blends, garnishes, non-alcoholic drinks, and cocktails.',
    'Raktachandini' : 'Pterocarpus santalinus, with the common names red sanders, red saunders, Yerra Chandanam, Chenchandanam, red sandalwood, Rakta Chandana, and rakto chandon, is a species of Pterocarpus endemic to the southern Eastern Ghats mountain range of South India. This tree is valued for the rich red colour of its wood, and in recent years there has been a marked uptick in the use of red sandalwood as a component of incense, especially in the west. The tree is not to be confused with the aromatic Santalum sandalwood trees that grow natively in Southern India. Pterocarpus santalinus is a light-demanding small tree, growing to 8 metres (26 ft) tall with a trunk 50–150 cm diameter. It is fast-growing when young, reaching 5 metres (16 ft) tall in three years, even on degraded soils. It is not frost tolerant, being killed by temperatures of −1 °C. The leaves are alternate, 3–9 cm long, trifoliate with three leaflets. The flowers are produced in short racemes. The fruit is a pod 6–9 cm long containing one or two seeds.',
    'Rose' : 'A rose is either a woody perennial flowering plant of the genus Rosa, in the family Rosaceae , or the flower it bears. There are over three hundred species and tens of thousands of cultivars. They form a group of plants that can be erect shrubs, climbing, or trailing, with stems that are often armed with sharp prickles. Their flowers vary in size and shape and are usually large and showy, in colours ranging from white through yellows and reds. Most species are native to Asia, with smaller numbers native to Europe, North America, and Northwest Africa. Species, cultivars and hybrids are all widely grown for their beauty and often are fragrant. Roses have acquired cultural significance in many societies. Rose plants range in size from compact, miniature roses to climbers that can reach seven meters in height. Different species hybridize easily, and this has been used in the development of the wide range of garden roses.',
    'Sapota' : 'Manilkara zapota, commonly known as sapodilla  sapote, chicozapote, chicoo, chicle, naseberry, nispero, or soapapple, among other names, is an evergreen tree native to southern Mexico and Central America. An example natural occurrence is in coastal Yucatán, in the Petenes mangroves ecoregion, where it is a subdominant plant species. It was introduced to the Philippines during Spanish colonization. It is grown in large quantities in Mexico and in tropical Asia, including India, Pakistan, Thailand, Malaysia, Cambodia, Indonesia, Vietnam, Bangladesh, as well as in the Caribbean. Most of the common names of Manilkara zapota like "sapodilla", "chiku", and "chicozapote" come from Spanish meaning "little sapote". Other common names in English include bully tree, soapapple tree, sawo, marmalade plum and dilly tree. Sapodilla trees can live up to one hundred years. It can grow to more than 30 m (98 ft) tall with a trunk diameter of up to 1.5 m (5 ft); but the average height of cultivated specimens is usually between 9 and 15 m (30 and 49 ft) with a trunk diameter not exceeding 50 cm (20 in). It is wind-resistant and the bark is rich in a white, gummy latex called chicle. Its leaves are elliptic to ovate 6–15 cm (2–6 in) long with entire margins on 1–3 cm (0–1 in) long petioles; they are medium green and glossy with brown and slightly furry midribs. They are arranged alternately.',
    'Tulasi' : 'Basil, (Ocimum tenuiflorum), flowering plant of the mint family (Lamiaceae) grown for its aromatic leaves. Holy basil is native to the Indian subcontinent and grows throughout Southeast Asia. The plant is widely used in Ayurvedic and folk medicine, often as an herbal tea for a variety of ailments, and is considered sacred in Hinduism. It is also used as a culinary herb with a pungent flavor that intensifies with cooking. It is reminiscent of clove, Italian basil (Ocimum basilicum), and mint and has a peppery spiciness. It is considered an agricultural weed and an invasive species in some areas outside its native range. The holy basil plant is a small annual or short-lived perennial shrub, up to 1 meter (3.3 feet) in height. The stems are hairy and bear simple toothed or entire leaves oppositely along the stem. The fragrant leaves are green or purple, depending on the variety. The small purple or white tubular flowers have green or purple sepals and are borne in terminal spikes. The fruits are nutlets and produce numerous seeds.',
    'Wood_sorel' : 'Wood sorrel, any of several flowering plants of the genus Oxalis (family Oxalidaceae). Common wood sorrel (Oxalis acetosella) of Europe and parts of Asia. The common wood sorrel (O. acetosella) of Europe and parts of Asia is a small stemless plant with cloverlike three-parted leaves that arise from a creeping scaly rootstock. The bisexual flowers are borne singly on a stalk that arises from the leaf axil. The flowers have five purple-veined white petals. The fruit is a capsule. The seeds have a fleshy coat, which curls back elastically, ejecting the true seed. The leaflets, as in other species of the genus, fold back and droop at night. In North America the name is chiefly used for mountain wood sorrel (O. montana), a stemless trifoliate (i.e., with three leaflets) herb native from southern Canada southward to Tennessee and westward to Minnesota. It grows about 15 cm (6 inches) tall and has pink-tinted stems and white or reddish flowers that appear from May until August. The name wood sorrel is sometimes inaccurately applied to sheep sorrel (Rumex acetosella) of the family Polygonaceae and to a West Indian begonia, Begonia acutifolia, of the family Begoniaceae.'
    # Add more plant information here...
}

plant_info = {
    'Aloevera': 'ಲೋಳೆಸರ (ಆಲೊವೆರಾ) ಒಂದು ರಸಭರಿತ ಜಾತಿಯ ಗಿಡ. ಇದರ ಹುಟ್ಟು ಆದದ್ದು ಉತ್ತರ ಆಫ್ರಿಕಾದಲ್ಲಿ. ಈ ಗಿಡವು ಕ್ರಿ.ಶ. ಒಂದನೆಯ ಶತಮಾನದಿಂದಲೂ ಒಂದು ಗಿಡಮೂಲಿಕೆಯ ಸಸ್ಯವೆಂದು ಕರೆಯಲ್ಪಟ್ಟಿದೆ. ಇದರ ರಸವನ್ನು ಊತ ಮತ್ತು ನೋವಿನ ಔಷಧವಾಗಿ ಬಳಸುವುದು ವಾಡಿಕೆಯಲ್ಲಿದೆ. ಈ ಸಸ್ಯವು ಸ್ವಾಭಾವಿಕವಾಗಿ ಹುಟ್ಟದೇ ಇದ್ದರೂ ಸಸ್ಯಗಳ ಗುಂಪಿನಲ್ಲಿ ಬೆಳೆದು ಬಂದಿದೆ ಎಂದು ಸಂಶೋಧನೆಗಳು ಹೇಳುತ್ತವೆ. ಕೆಲವು ವೈಜ್ಞಾನಿಕ ಸಂಶೋಧನೆಗಳ ಪ್ರಕಾರ ಇದರ ರಸವನ್ನು ಸೌಂದರ್ಯವರ್ಧಕ ಹಾಗೂ ಔಷಧಕ್ಕಾಗಿ ಬಳಸಬಹುದೆಂದು ಹೇಳಲಾಗಿದೆ. ಜೀರ್ಣಕ್ರಿಯ ವೃದ್ಧಿ ಆಗುವದಕ್ಕು, ಎದೆ ಉರಿಯನ್ನು ಕಡೆಮೆಮಾಡುವುದರಲ್ಲಿ, ಮತ್ತು ಅಜೀರ್ಣ ಕಾರಣವಾಗಿ ಬರುವ ವ್ಯಾಧಿಗಳ ನಿವಾರಣೆಗೆ ಇದರ ರಸ ಚೆನ್ನಾಗಿ ಕೆಲಸಮಾಡುತ್ತದೆ.ಎಲೆಗಳಿಂದ ಅನೇಕ ಶಾಂಪೂಗಳನ್ನೂ ತಯಾರಿಸುತ್ತಾರೆ. ಎಲೆಗಳಿಂದ ತಯಾರಿಸಿದ ಬಾರ್‌ಬೆಲಿಯಾನ್ ಎಂಬ ಜೀವನಿರೋಧಕವನ್ನು ಕ್ಷಯರೋಗಕಾರಕ ಬ್ಯಾಕ್ಟೀರಿಯಗಳನ್ನು ನಾಶಮಾಡಲು ಬಳಸಲಾಗುತ್ತದೆ.  ',
    'Amla': 'ಆಮ್ಲಾವನ್ನು ಅದರ ಸಮೃದ್ಧವಾದ ಉತ್ಕರ್ಷಣ ನಿರೋಧಕ ಮತ್ತು ಕಬ್ಬಿಣದ ಅಂಶದಿಂದಾಗಿ ಬಹಳಷ್ಟು ಶ್ಯಾಂಪೂಗಳು ಮತ್ತು ಕಂಡಿಷನರ್‌ಗಳಲ್ಲಿ ಬಳಸಲಾಗುತ್ತದೆ. ಭಾರತೀಯ ನೆಲ್ಲಿಕಾಯಿಯು ಹೆಚ್ಚಿನ ಮಟ್ಟದ ವಿಟಮಿನ್ ಸಿ ಅನ್ನು ಹೊಂದಿರುತ್ತದೆ ಇದು ಕೂದಲು ಉದುರುವಿಕೆಯನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಇದು ಬೇರುಗಳನ್ನು ಬಲಪಡಿಸುತ್ತದೆ ಮತ್ತು ಕೂದಲಿನ ಬಣ್ಣವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳುತ್ತದೆ. ನೆಲ ನೆಲ್ಲಿಕಾಯಿಯಲ್ಲಿ ಹೆಚ್ಚಿನ ಪ್ರಮಾಣದ ವಿಟಮಿನ್ ಸಿ ಇರುವುದರಿಂದ, ಇದು ದೇಹವನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಆರೋಗ್ಯಕರವಾಗಿರಿಸುತ್ತದೆ. ಪಿತ್ತಜನಕಾಂಗದ ತೊಂದರೆಗಳು, ಜ್ವರ ಮತ್ತು ಕಾಮಾಲೆಯನ್ನು ಕಡಿಮೆ ಮಾಡುವಲ್ಲಿ ಪರಿಣಾಮಕಾರಿ. ಇವುಗಳಲ್ಲಿರುವ ಉರಿಯೂತ ನಿವಾರಕ, ಆ್ಯಂಟಿ ಬಯೋಟಿಕ್ ಮತ್ತು ಅಸ್ತಮಾ ನಿವಾರಕ ಗುಣಗಳು ಉಸಿರಾಟದ ತೊಂದರೆಗಳನ್ನು ತಡೆಯುತ್ತದೆ. ಇದರಿಂದ ಶೀತ, ಗಂಟಲು ನೋವು, ಕೆಮ್ಮು ಮತ್ತು ಜ್ವರದಂತಹ ಸಮಸ್ಯೆಗಳು ಬರುವುದಿಲ್ಲ. ಇದು ಎದೆ ಮತ್ತು ಮೂಗಿನ ಕುಳಿಗಳ ಸಮಸ್ಯೆಗಳಿಗೆ ಪರಿಹಾರವನ್ನು ನೀಡುತ್ತದೆ. ಮತ್ತು ಸುಲಭವಾಗಿ ಉಸಿರಾಟಕ್ಕೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಇದರೊಂದಿಗೆ, ಇದು ಚರ್ಮಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ಸಮಸ್ಯೆಗಳನ್ನು ತಡೆಯುತ್ತದೆ ಮತ್ತು ಚರ್ಮದ ಆರೋಗ್ಯ ಕಾಯ್ದುಕೊಳ್ಳಲು ಸಾಧ್ಯವಾಗುತ್ತದೆ.',
    'Arali' : 'ಅರಳಿಮರ ಮೊರೇಸೀ ಕುಟುಂಬಕ್ಕೆ ಸೇರಿದ ಮರ (ಫೈಕಸ್ ರಿಲಿಜಿಯೋಸ ಇದರ ವೈಜ್ಞಾನಿಕ ಹೆಸರು.) ಅಶ್ವತ್ಥವೃಕ್ಷ ಇದರ ಪರ್ಯಾಯನಾಮ. ಉಗಮಸ್ಥಾನ ಭಾರತ. ಹಲವು ಶತಮಾನಗಳ ಕಾಲ ಇದು ಜೀವಂತವಾಗಿದ್ದ ದಾಖಲೆಗಳಿವೆ. ಪ್ರ ಶ.ಪೂ. 288ರಲ್ಲಿ ನೆಟ್ಟ ಒಂದು ಮರ ಶ್ರೀಲಂಕದಲ್ಲಿ ಇದ್ದಿತು. ವಿದುರಾಶ್ವತ್ಥದಲ್ಲಿರುವ ಅರಳಿಮರವೂ ಬಹು ಹಳೆಯದು. ಅರಳಿ ಮರ ಉಳಿದ ಜಾತಿಯ ಮರಗಳಿಗಿಂತ ಹೆಚ್ಚು ಆಮ್ಲಜನಕವನ್ನು ಉತ್ಪಾದಿಸುವ ಸಾಮರ್ಥ್ಯವನ್ನು ಹೊಂದಿದೆ. ಬೇರೆ ಮರಗಳು ಕೇವಲ ಸೂರ್ಯನ ಬೆಳಕಿನಲ್ಲಿ ಮಾತ್ರ ದ್ಯುತಿಸಂಶ್ಲೇಷಣಾ ಕ್ರಿಯೆ ನಡೆಸಿದರೆ, ಅರಳಿ ಮರ ಚಂದ್ರನ ಬೆಳಕಿನಲ್ಲೂ ಈ ಕ್ರಿಯೆಯನ್ನು ನಡೆಸುವ ಸಾಮರ್ಥ್ಯ ಹೊಂದಿದೆ. ಹಾಗಾಗಿ ಇದು ಸಸ್ಯಗಳಲ್ಲೇ ಪ್ರಾಮುಖ್ಯವಾದ ಭೇಧ. ನಗರದ ವಾಯುಮಾಲಿನ್ಯ ನಿಯಂತ್ರಣದಲ್ಲಿ ಈ ಮರಗಳ ಕೊಡುಗೆ ಮಹತ್ವದ್ದು. ಇದರ ತೊಗಟೆಯ ಕಷಾಯವನ್ನು ಕಜ್ಜಿ ಹುಣ್ಣುಗಳಿಗೆ ಔಷಧವಾಗಿ ಬಳಸುವುದುಂಟು. ಅರಳಿಮರಗಳನ್ನು ತೋಟಗಳಲ್ಲೂ ದೇವಸ್ಥಾನಗಳ ಪರಿಸರದಲ್ಲೂ ಹೆದ್ದಾರಿಯ ಇಬ್ಬದಿಗಳಲ್ಲೂ ನೆರಳಿಗಾಗಿ ಬೆಳೆಸುತ್ತಾರೆ.',
    'Ashoka': 'ಅಶೋಕ, ಒಂದು ಮಧ್ಯಮ ಗಾತ್ರದ ನಿತ್ಯ ಹಸುರಿನ ಸುಂದರವಾದ ಮರ. ಅಶೋಕ ನಿಧಾನವಾಗಿ ಬೆಳೆಯುವ ಮರ. ೬-೮ ಮೀಟರ್ ಎತ್ತರ ಬೆಳೆಯುತ್ತದೆ. ನೀಳವಾಗಿ ಚೂಪಾಗಿರುವ ಎಲೆಗಳಿಂದ ಕೂಡಿದ ಮರದ ತುಂಬಾ ಗೊಂಚಲ ಗೊಂಚಲ ಹೂಗಳ ಗೊಂಚಲುಗಳು, ಮನಸ್ಸಿಗೆ ಮುದನೀಡುತ್ತವೆ. ಈ ಗಿಡದ ಕಾಯಿಗಳು ಕಂದು ಬಣ್ಣದವು. ಹತ್ತು ಸೆಂಟಿಮೀಟರ್ ಉದ್ದವಾಗಿರುವ ಕಾಯಿಗಳ ಒಳಗಡೆ ಸಾಲಾಗಿ ಬೀಜಗಳಿರುತ್ತವೆ. ಸಮುದ್ರಮಟ್ಟದಿಂದ ೨-೩ ಸಾವಿರ ಅಡಿ ಎತ್ತರದ ಪೂರ್ವ, ಈಶಾನ್ಯ ಭಾರತದ ಕಾಡುಗಳಲ್ಲಿ ಹೇರಳವಾಗಿ ಕಂಡುಬರುತ್ತವೆ. ಕರ್ಣಾಟಕದಲ್ಲೂ ಇದು ವಿಶೇಷವಾಗಿ ಕಾಣಬರುವ ಸಸ್ಯರಾಶಿ. ಇದು ದೇಹದ ರಕ್ತವನ್ನು ಸ್ವಚ್ಛಗೊಳಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಇದರ ಪರಿಣಾಮವೆಂದರೆ ಇದು ಚರ್ಮವನ್ನು ಹೊಳೆಯುವಂತೆ ಮಾಡುತ್ತದೆ. ಒಟ್ಟಾರೆ ತ್ವಚೆಯನ್ನು ಆರೋಗ್ಯವಾಗಿರಿಸುತ್ತದೆ. ಅಶೋಕ ಎಲೆಗಳಲ್ಲಿಯೂ ಹೈಪೊಗ್ಲಿಸಿಮಿಕ್ ಗುಣಗಳು ಹೇರಳವಾಗಿ ಕಂಡುಬರುತ್ತವೆ. ಇದನ್ನು ಸೇವಿಸಿದರೆ, ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆಯ ಮಟ್ಟವನ್ನು ಕಡಿಮೆ ಮಾಡಬಹುದು. ಅಶೋಕ ಮರದ ಎಲೆಯ ಪರಿಣಾಮವಾಗಿ ದೇಹದಲ್ಲಿ ಇನ್ಸುಲಿನ್ ಉತ್ಪಾದನೆಯ ಕ್ರಿಯೆಯು ಸುಧಾರಿಸುತ್ತದೆ.',
    'Ashwagandha': ' ಅಶ್ವಗಂಧಾ ಎಂಬುದು ಒಂದು ಔಷಧಿಗಿಡ. ಹಿರಿಯರಿಂದ ಹಿರೇಮದ್ದು ಎಂದೇ ಕರೆಸಿಕೊಳ್ಳುವ ಈ ಸಸ್ಯ, ನರಸಂಬಂಧಿ, ಕಫ ವಾತ ಸಂಬಂಧಿ ದೋಷಗಳನ್ನು ಕಿತ್ತು ಕಳೆಯಬಲ್ಲ ಗುಣವಿದೆ. ಈ ಗಿಡದ ಬೇರಿಗೆ ಲೈಂಗಿಕ ದೌರ್ಬಲ್ಯ ನಿವಾರಿಸುವ ಅದ್ಬುತ ಸಾಮರ್ಥ್ಯವಿದೆ. ಹಾವು, ಚೇಳು ಕಚ್ಚಿದಾಗ ಇದರ ಬೇರನ್ನು ನಿಂಬೇ ರಸದೊಂದಿಗೆ ಹಚ್ಚಲು ಉಪಯೋಗಿಸುತ್ತಾರೆ. ಆಯುರ್ವೇದ ಪಂಡಿತರು ಸಂಸ್ಕೃತದಲ್ಲಿ ಇದಕ್ಕೆ ನೀಡಿದ ಹೆಸರು ವಾಜೀಗಂಧಾ, ಹಯಗಂಧಾ, ವರಾಹಕರ್ಣೀ ಇತ್ಯಾದಿ. ಎಲೆ ಹಣ್ಣು ಮತ್ತು ಬೇರು ಚಿಕಿತ್ಸೆಗಳಲ್ಲಿ ಉಪಯೋಗಿಸುವರು. ಬಹು ಹಿಂದಿನ ಕಾಲದಿಂದಲೂ ಬಳಕೆಯಲ್ಲಿರುವ ಔಷಧಿ. ಬೇರಿನಲ್ಲಿ ಸೋಮ್ನಿಫೆರಸ್ ಅನ್ನುವ ಕ್ಷಾರವಿರುವುದು. ಈ ಕ್ಷಾರವು ನಿದ್ದೆ ಬರಿಸುವ ಸಾಮರ್ಥ್ಯ ಹೊಂದಿದೆ. ಸರ್ವ ರೋಗಕ್ಕೆ ಮದ್ದು ಹಿರೇಮದ್ದು ಎಂದು ನಾಣ್ನುಡಿ. ಸತ್ಯವೂ ಹೌದು. ಇದು ರಕ್ತ ಶುದ್ಧಿ ಮಾಡಿ, ರಕ್ತ ವೃದ್ಧಿ ಮಾಡಿ ದೇಹಕ್ಕೆ ಕಾಂತಿ ಮತ್ತು ಪುಷ್ಟಿಯನ್ನು ಕೊಡುವುದು. ನಿಶ್ಶಕ್ತಿಯನ್ನು ನೀಗುವುದು ಹಾಗೂ ಗೆಲ್ಲುವ ಶಕ್ತಿಯಿದೆ. ಈ ವನೌಷಧಿ ಸೇವನೆಯಿಂದ ಸಂವೋಹಕಾರಿ ಚಿತ್ತ ಚಂಚಲತೆ, ಗಾಬರಿ ದೂರವಾಗುವುವು. ಮಕ್ಕಳಿಗೆ ಪುಷ್ಟಿ ನೀಡಿವುದು, ವೃದ್ಧಾಪ್ಯದ ದೌರ್ಬಲ್ಯಗಳನ್ನು ನೀಗಿ ಶಕ್ತಿ, ಸ್ಫೂರ್ತಿ ಮತ್ತು ಯೌವನವನ್ನು ಕೊಡುವುದು.',
    'Avacado' : 'ಆವಕಾಡೊ , ( ಪರ್ಸಿಯಾ ಅಮೇರಿಕಾನಾ ), ಲಾರೇಸಿ ಕುಟುಂಬದ ಮರ ಮತ್ತು ಅದರ ಖಾದ್ಯ ಹಣ್ಣು . ಆವಕಾಡೊಗಳು ಪಶ್ಚಿಮ ಗೋಳಾರ್ಧದಲ್ಲಿ ಮೆಕ್ಸಿಕೋ ದಕ್ಷಿಣದಿಂದ ಆಂಡಿಯನ್ ಪ್ರದೇಶಗಳಿಗೆ ಸ್ಥಳೀಯವಾಗಿವೆ ಮತ್ತು ಬೆಚ್ಚಗಿನ ವಾತಾವರಣದಲ್ಲಿ ವ್ಯಾಪಕವಾಗಿ ಬೆಳೆಯಲಾಗುತ್ತದೆ. ಸಸ್ಯಜನ್ಯ ಎಣ್ಣೆಗಳನ್ನು ಆಹಾರ ಮತ್ತು ಆಹಾರ ತಯಾರಿಕೆಯಲ್ಲಿ ವ್ಯಾಪಕವಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ. ಉದಾಹರಣೆಗೆ, ಆಲಿವ್ ಎಣ್ಣೆಯನ್ನು ಸುಮಾರು 8,000 ವರ್ಷಗಳಿಂದ ಉತ್ಪಾದಿಸಲಾಗುತ್ತದೆ. ಸಸ್ಯಜನ್ಯ ಎಣ್ಣೆಗಳನ್ನು ಸಾಮಾನ್ಯವಾಗಿ ತರಕಾರಿಗಳು ಮತ್ತು ಮಾಂಸವನ್ನು ಹುರಿಯಲು ಅಥವಾ ಹುರಿಯಲು ಬಳಸಲಾಗುತ್ತದೆ ಮತ್ತು ವಿವಿಧ ಸಾಸ್‌ಗಳು ಮತ್ತು ಬೇಯಿಸಿದ ಸರಕುಗಳಲ್ಲಿ ಪ್ರಮುಖ ಅಂಶವಾಗಿದೆ. ಸಸ್ಯಜನ್ಯ ಎಣ್ಣೆಗಳನ್ನು ಮಾರ್ಗರೀನ್‌ನಲ್ಲಿ ಬಳಸಲಾಗುತ್ತದೆ. ',
    'Bamboo' : 'ಬಿದಿರುಗಳು ಬಹುಪಾಲು ನಿತ್ಯಹರಿದ್ವರ್ಣ ಬಹುವಾರ್ಷಿಕ ಹೂಬಿಡುವ ಸಸ್ಯಗಳ ವೈವಿಧ್ಯಮಯ ಗುಂಪಾಗಿದ್ದು, ಇದು ಹುಲ್ಲಿನ ಕುಟುಂಬದ ಪೊಯೇಸಿಯ ಉಪಕುಟುಂಬವನ್ನು ಬಂಬುಸೊಯ್ಡೆಯನ್ನು ರೂಪಿಸುತ್ತದೆ . ಬಿದಿರು ಕಾಡು ಬೆಳೆಯಾದರೂ, ಈಗೀಗ ಶೃಂಗಾರಕ್ಕೆಂದು ಅದನ್ನು ಉದ್ಯಾನವನಗಳಲ್ಲೂ ಮನೆಯಂಗಳದಲ್ಲೂ ಬೆಳೆಯುತ್ತಿದ್ದಾರೆ. ಕಾಗದದ ತಯಾರಿಕೆಯಲ್ಲಿ ಹಾಗೂ ರಯಾನ್ ಬಟ್ಟೆಯತಯಾರಿಕೆಯಲ್ಲಿ. ಮನೆಗಳ ನಿರ್ಮಾಣದಲ್ಲಿ. ತೆಪ್ಪ, ದೋಣಿ, ಹಾಯಿ ಪಟಗಳಿಗಾಗಿ,ದೀಪದ ಕಂಬ, ಏಣಿ, ತೊಟ್ಟಿಲು, ಕೊಳಲುವಾದನದ ತಯಾರಿಕೆಯಲ್ಲಿ. ಕೃಷಿಯಲ್ಲಿ ಬಳಸುವ ವಿವಿಧ ಉಪಕರಣಗಳಲ್ಲಿ. ಪೀಠೋಪಕರಣಗಳ ತಯಾರಿಕೆಯಲ್ಲಿ- ಕುರ್ಚಿ, ಮೇಜು, ಚಾಪೆ, ಬುಟ್ಟಿ, ಶಾಮಿಯಾನ, ಮೊರ, ಮಂಕರಿ, ಬೀಸಣಿಗೆ, ಕಟ್ಟಡಗಳನ್ನು ದುರಸ್ತಿಮಾಡುವಾಗ ಕಟ್ಟುವಾಗ, ಬಿದಿರಿನ ಅಟ್ಟಳಿಕೆ ಅಗತ್ಯ. ಬಿದಿರಿನ ಚಿಗುರೆಲೆಯನ್ನು ಚೆನ್ನಾಗಿಜಜ್ಜಿ, ಗಾಯ ಹಾಗೂ ಬಾವು ಇಳಿಸಲು ಲೇಪ ಹಾಕುತ್ತಾರೆ. ಎಳೆ-ಬಿದುರಿನ ಕಷಾಯವು ಕೆಮ್ಮುನಿವಾರಕ.',
    'Basale' : 'ಬಸಳೆ (ಬ್ಯಾಸೆಲಾ ಆಲ್ಬಾ) ಬಸೆಲೇಸಿಯಿ (ಬ್ಯಾಸೆಲೇಸೀ) ಕುಟುಂಬದಲ್ಲಿನ ಒಂದು ತಿನ್ನಲರ್ಹ ಬಹುವಾರ್ಷಿಕ ಬಳ್ಳಿ (ಇಂಡಿಯನ್ ಸ್ಪಿನಿಚ್). ಇದು ಏಷ್ಯಾದ ಉಷ್ಣವಲಯ ಮತ್ತು ಆಫ್ರಿಕಾದಲ್ಲಿ ಕಾಣಸಿಗುತ್ತದೆ. ಬಸಳೆಯು ಪೌಷ್ಟಿಕಾಂಶಭರಿತವಾಗಿದೆ. ಇದರ ಎಳೆಯ ಕಾಂಡ ಮತ್ತು ಎಲೆಗಳನ್ನು ಸೊಪ್ಪು ತರಕಾರಿಯಂತೆ ಹಸಿಯಾಗಿಯೊ ಬೇಯಿಸಿಯೊ ಉಪಯೋಗಿಸುವುದಿದೆ. ಇದರಲ್ಲಿ ಪ್ರತಿಯೊಂದು 100 ಗ್ರಾಮಿಗೆ 1.2% ಪ್ರೋಟೀನ್, 0.15% ಕ್ಯಾಲ್ಸಿಯಮ್, 1.4 ಮಿಲಿ ಗ್ರಾಮ್ ಕಬ್ಬಿಣ, 3250 IU ವಿಟಮಿನ್ A ಇವೆ. ಬಸಳೆ ಸೊಪ್ಪಿನಲ್ಲಿ ವಿಟಮಿನ್ ಎ ಅಧಿಕವಾಗಿದೆ. (100 ಗ್ರಾಂನಲ್ಲಿ ಸರಿಸುಮಾರು 8,000 ಘಟಕಗಳು) ಇದರಲ್ಲಿ ಉತ್ತಮ ಪ್ರಮಾಣದ ಆ್ಯಂಟಿಆಕ್ಸಿಡೆಂಟ್‌ಗಳಿವೆ, ವಿಶೇಷವಾಗಿ ಬೀಟಾ ಕ್ಯಾರೋಟಿನ್ ಮತ್ತು ಲುಟೀನ್, ನೈಸರ್ಗಿಕವಾಗಿ ಸಿಗುವ ರಾಸಾಯನಿಕಗಳು ನಿಮ್ಮ ಜೀವಕೋಶಗಳನ್ನು ವಯಸ್ಸಾಗದಂತೆ ನೋಡಿಕೊಳ್ಳುತ್ತವೆ. ಇದರ ಜೊತೆಗೆ ವಿಟಮಿನ್ ಸಿ, ಕಬ್ಬಿಣ ಮತ್ತು ಕ್ಯಾಲ್ಸಿಯಂನಿಂದ ಸಮೃದ್ಧವಾಗಿದೆ. ಬಸಳೆ ಸೊಪ್ಪಿನ ಅಡಕವಾಗಿರುವ ವಿಟಮಿನ್ ಕೆ ಮೂಳೆಯ ಆರೋಗ್ಯಕ್ಕೆ ಸಹಕಾರಿಯಾಗಿದೆ. ಇದು ದೇಹದಿಂದ ಕ್ಯಾಲ್ಸಿಯಂ ಹೀರಿಕೊಳ್ಳುವಿಕೆಯನ್ನು ಸುಧಾರಿಸುತ್ತದೆ. ಮತ್ತು ಬಸಳೆಸೊಪ್ಪು ಪ್ರತಿ 250 ಮಿಗ್ರಾಂ ಕ್ಯಾಲ್ಸಿಯಂ ಅನ್ನು ಹೊಂದಿರುತ್ತದೆ.',
    'Betel' : 'ವೀಳ್ಯದೆಲೆ ( ಪೈಪರ್ ಬೆಟಲ್ ) ಆಗ್ನೇಯ ಏಷ್ಯಾಕ್ಕೆ ಸ್ಥಳೀಯವಾಗಿರುವ ಪೈಪೆರೇಸಿ ಕುಟುಂಬದಲ್ಲಿ ಹೂಬಿಡುವ ಸಸ್ಯದ ಜಾತಿಯಾಗಿದೆ . ಕರಾವಳಿ ಕರ್ನಾಟಕದಲ್ಲಿ ತುಳುವರ ಎಲ್ಲಾ ಶುಭಕಾರ್ಯಗಳಿಗೂ ಎಲೆ ಅಡಿಕೆ ಬೇಕೇಬೇಕು. ಚಿಗುರು ವೀಳ್ಯದೆಲೆ, ವಾತಹರ, ಉದರ ವಾಯುಹರ ಮತ್ತು ಉತ್ತೇಜನಕಾರಿ. ಇದು ಕಾಮೋತ್ತೇಜಕವಾಗಿದ್ದು ಸೋಂಕನ್ನು ತಡೆಗಟ್ಟುವ ಗುಣವನ್ನೂ ಹೊಂದಿದೆ. ಜೀರ್ಣಶಕ್ತಿ ಹೆಚ್ಚಿಸಿ, ಧ್ವನಿ ಸರಿಪಡಿಸಿ, ಗ್ಯಾಸ್ಟ್ರಿಕ್ ಟ್ರಬಲ್ ನ್ನು ಬಹುಮಟ್ಟಿಗೆ ಗುಣಪಡಿಸುತ್ತದೆ. ಮಕ್ಕಳಲ್ಲಿನ ಕೆಮ್ಮು ಮತ್ತು ಅಜೀರ್ಣಕ್ಕೆ ಈ ಎಲೆಯ ರಸ ಉಪಯೋಗ. ಸಣ್ಣ ಮಕ್ಕಳಲ್ಲಿ ಉಸಿರಾಟದ ತೊಂದರೆಯಾದಾಗ ಎಣ್ಣೆ ಸವರಿ, ಬಾಣಲೆಯಲ್ಲಿ ಬೆಚ್ಚಗೆ ಮಾಡಿದ ವೀಳ್ಯದೆಲೆಯನ್ನು ಎದೆಯ ಮೇಲಿಡುವುದು ಪ್ರಯೋಜನಕಾರಿ.',
    'Betel_Nut': 'ವೀಳ್ಯದೆಲೆ ಅರೆಕಾ ಎಂಬ ಸಸ್ಯದಿಂದ ಬರುವ ಕಾಯಿ. ಇದನ್ನು ಕೆಲವೊಮ್ಮೆ ಔಷಧಿ ತಯಾರಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ. ವೀಳ್ಯದೆಲೆಯನ್ನು ಏಕಾಂಗಿಯಾಗಿ ಅಥವಾ ಕ್ವಿಡ್ಸ್ ರೂಪದಲ್ಲಿ ಅಗಿಯಲಾಗುತ್ತದೆ, ತಂಬಾಕು ಮಿಶ್ರಣ , ಪುಡಿಮಾಡಿದ ಅಥವಾ ಕತ್ತರಿಸಿದ ವೀಳ್ಯದೆಲೆ ಮತ್ತು ಇತರ ಪದಾರ್ಥಗಳು. ವೀಳ್ಯದೆಲೆಯನ್ನು ಬಳಸುವುದು ಕೂಡ ಅಸುರಕ್ಷಿತವಾಗಿರಬಹುದು. ಕೆಲವರು ವೀಳ್ಯದೆಲೆಯನ್ನು ಮನರಂಜನಾ ಔಷಧವಾಗಿ ಬಳಸುತ್ತಾರೆ ಏಕೆಂದರೆ ಇದು ಕೇಂದ್ರ ನರಮಂಡಲದ (CNS) ವೇಗವನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ. ವೀಳ್ಯದೆಲೆಯನ್ನು ಅಗಿಯುವುದು ಸ್ಕಿಜೋಫ್ರೇನಿಯಾದ ಕೆಲವು ಜನರಲ್ಲಿ ರೋಗಲಕ್ಷಣಗಳನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ ಎಂದು ಸೂಚಿಸುತ್ತದೆ. ಆದರೆ ವೀಳ್ಯದೆಲೆಯನ್ನು ದೀರ್ಘಕಾಲದವರೆಗೆ ಬಳಸುವುದು ಅಸುರಕ್ಷಿತವಾಗಿದೆ. ಜೀರ್ಣಕ್ರಿಯೆಗೆ ಸಹಕಾರಿ.',
    'Brahmi' : 'ಬ್ರಾಹ್ಮಿ ಅಥವಾ ಒಂದೆಲಗ ಎನ್ನುವುದು ಹಲವಾರು ವಿಧದ ಔಷಧೀಯ ಗುಣಗಳನ್ನು ಹೊಂದಿರುವಂತಹ ಒಂದು ಅದ್ಭುತ ಸೊಪ್ಪು. ಇದನ್ನು ಹಿಂದಿನಿಂದಲೂ ಆಹಾರ ಕ್ರಮ ಹಾಗೂ ಔಷಧಿಯಾಗಿ ಬಳಕೆ ಮಾಡಲಾಗುತ್ತದೆ. ಮಕ್ಕಳಲ್ಲಿ ಏಕಾಗ್ರತೆ ಹಾಗೂ ಸ್ಮರಣ ಶಕ್ತಿ ವೃದ್ಧಿ, ಕಲಿಕೆಯ ಶಕ್ತಿ ಹೆಚ್ಚಿಸಲು, ದೊಡ್ಡವರಲ್ಲೂ ಮಾನಸಿಕ ಒತ್ತಡದ ನಿವಾರಣೆಗೆ ಇದು ಸಹಾಯಕಾರಿ. ಮಾನಸಿಕ ಒತ್ತಡವು ಹೆಚ್ಚಾದರೆ ಅದು ಇನ್ನಿತರ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳನ್ನು ಉಂಟು ಮಾಡುವುದು. ಈ ಕಾರಣ ಮಾನಸಿಕ ಒತ್ತಡವನ್ನು ನಿಯಂತ್ರಣದಲ್ಲಿ ಇಟ್ಟುಕೊಳ್ಳುವುದು ಅತೀ ಅಗತ್ಯ. ಮಾನಸಿಕ ಒತ್ತಡವನ್ನು ನಿಯಂತ್ರಿಸಲು ಆಯುರ್ವೇದದಲ್ಲಿ ಬ್ರಾಹ್ಮಿಯನ್ನು ಬಳಸಲಾಗಿದೆ. ಬ್ರಾಹ್ಮಿ ತುಂಬಾ ಪರಿಣಾಮಕಾರಿ ಔಷಧಿಯಾಗಿದ್ದು, ಇದು ಚಿಕಿತ್ಸಕ ಗುಣ ಹೊಂದಿದೆ ಹಾಗೂ ಮನಸ್ಸಿಗೆ ಕೂಡ ಶಮನ ನೀಡುವುದು. ಇದು ನರವ್ಯವಸ್ಥೆಯನ್ನು ಸುಧಾರಣೆ ಮಾಡಿಕೊಂಡು ಮೆದುಳಿನ ಕಾರ್ಯವನ್ನು ಉತ್ತಮಪಡಿಸುವುದು.',
    'Castor' : 'ಕ್ಯಾಸ್ಟರ್-ಆಯಿಲ್ ಪ್ಲಾಂಟ್ , ( ರಿಸಿನಸ್ ಕಮ್ಯುನಿಸ್ ), ಸ್ಪರ್ಜ್ ಕುಟುಂಬದ ದೊಡ್ಡ ಸಸ್ಯ ( ಯುಫೋರ್ಬಿಯೇಸಿ ), ಅದರ ತೈಲದ ಔಷಧೀಯ ಮತ್ತು ಕೈಗಾರಿಕಾ ಬಳಕೆಗಾಗಿ ಮತ್ತು ಭೂದೃಶ್ಯದ ಬಳಕೆಗಾಗಿ ವಾಣಿಜ್ಯಿಕವಾಗಿ ಬೆಳೆಯಲಾಗುತ್ತದೆ. ಬಹುಶಃ ಉಷ್ಣವಲಯದ ಆಫ್ರಿಕಾಕ್ಕೆ ಸ್ಥಳೀಯವಾಗಿದೆ, ಕ್ಯಾಸ್ಟರ್-ಆಯಿಲ್ ಸಸ್ಯವು ಪ್ರಪಂಚದ ಬೆಚ್ಚಗಿನ ಪ್ರದೇಶಗಳಲ್ಲಿ ನೈಸರ್ಗಿಕವಾಗಿ ಮಾರ್ಪಟ್ಟಿದೆ. ಸಸ್ಯಗಳನ್ನು ಮುಖ್ಯವಾಗಿ ಭಾರತ , ಚೀನಾ ಮತ್ತು ಬ್ರೆಜಿಲ್‌ನಲ್ಲಿ ಬೆಳೆಸಲಾಗುತ್ತದೆ , ಹೆಚ್ಚಾಗಿ ಮೂಲವಾಗಿಕ್ಯಾಸ್ಟರ್ ಆಯಿಲ್ . ಸಸ್ಯವು ಅದರ ಕುಲದಲ್ಲಿ ಏಕೈಕ ಜಾತಿಯಾಗಿದ್ದರೂ , ನೂರಾರು ನೈಸರ್ಗಿಕ ರೂಪಗಳು ಮತ್ತು ಅನೇಕ ತೋಟಗಾರಿಕಾ ಪ್ರಭೇದಗಳಿವೆ. ಎಣ್ಣೆಯುಕ್ತ ಬೀಜಗಳು ವಿಷವನ್ನು ಹೊಂದಿರುತ್ತವೆ ricin , ತಿಳಿದಿರುವ ಅತ್ಯಂತ ವಿಷಕಾರಿ ಪದಾರ್ಥಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ ಮತ್ತು ಅಗಿಯುವ ಬೀಜಗಳ ಸೇವನೆಯು ಮಾರಕವಾಗಬಹುದು. ಉಷ್ಣವಲಯದಲ್ಲಿ ಸಸ್ಯಗಳು ಸುಮಾರು 10 ರಿಂದ 13 ಮೀಟರ್ (30 ರಿಂದ 40 ಅಡಿ) ಎತ್ತರವನ್ನು ತಲುಪುತ್ತವೆ. ಸಮಶೀತೋಷ್ಣ ಹವಾಮಾನದಲ್ಲಿ ಅವುಗಳನ್ನು ವಾರ್ಷಿಕವಾಗಿ ಬೆಳೆಸಲಾಗುತ್ತದೆ ಮತ್ತು ಒಂದೇ ಋತುವಿನಲ್ಲಿ 1.5 ರಿಂದ 2.5 ಮೀಟರ್ (4.9 ರಿಂದ 8 ಅಡಿ) ಬೆಳೆಯುತ್ತದೆ. ಸಸ್ಯಗಳು ಸುಂದರವಾದ ದೈತ್ಯ 12-ಹಾಲೆಗಳ ಪಾಮೇಟ್ (ಅಭಿಮಾನಿಗಳಂತಹ) ಎಲೆಗಳನ್ನು ಹೊಂದಿರುತ್ತವೆ. ಕಂಚಿನಿಂದಲೂ ಕೆಂಪು ಬಣ್ಣದ ಹಣ್ಣುಗಳ ಗೊಂಚಲುಗಳು ಆಕರ್ಷಕವಾಗಿರುತ್ತವೆ ಆದರೆ ಅವುಗಳು ಪಕ್ವವಾಗುವ ಮೊದಲು ತೆಗೆದುಹಾಕಲ್ಪಡುತ್ತವೆ, ಏಕೆಂದರೆ ಅವುಗಳ ಮಚ್ಚೆಯುಳ್ಳ ಹುರುಳಿ ಬೀಜಗಳಲ್ಲಿ ಕೇಂದ್ರೀಕೃತವಾಗಿರುವ ರಿಸಿನ್ ಕಾರಣ .',
    'Curry_Leaf' : 'ಕರಿಬೇವಿನ ಎಲೆಗಳು, ಕಡಿ ಪಟ್ಟ ಅಥವಾ ಸಿಹಿ ಬೇವಿನ ಎಲೆಗಳು ಎಂದೂ ಕರೆಯಲ್ಪಡುವ ಸುಗಂಧ ದ್ರವ್ಯಗಳನ್ನು ಸಾಮಾನ್ಯವಾಗಿ ಭಾರತೀಯ ಪಾಕಪದ್ಧತಿಯಲ್ಲಿ ವಿವಿಧ ಭಕ್ಷ್ಯಗಳಿಗೆ ಸುವಾಸನೆ ಮತ್ತು ಪರಿಮಳವನ್ನು ಸೇರಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ. ಅವು ಭಾರತ ಮತ್ತು ಶ್ರೀಲಂಕಾಕ್ಕೆ ಸ್ಥಳೀಯವಾಗಿರುವ ಕರಿಬೇವಿನ ಮರದಿಂದ (ಮುರ್ರಾಯ ಕೊಯೆನಿಗಿ) ಬರುತ್ತವೆ. ಈ ಎಲೆಗಳು ಸ್ಪಷ್ಟವಾಗಿ ಸಿಟ್ರಸ್ ಮತ್ತು ಸ್ವಲ್ಪ ಕಹಿ ರುಚಿಯನ್ನು ಹೊಂದಿರುತ್ತವೆ ಮತ್ತು ಇದನ್ನು ಹೆಚ್ಚಾಗಿ ದಕ್ಷಿಣ ಭಾರತದ ಅಡುಗೆಗಳಲ್ಲಿ, ವಿಶೇಷವಾಗಿ ಮೇಲೋಗರಗಳು, ಚಟ್ನಿಗಳು, ಅಕ್ಕಿ ಭಕ್ಷ್ಯಗಳು ಮತ್ತು ಸೂಪ್‌ಗಳಲ್ಲಿ ಬಳಸಲಾಗುತ್ತದೆ. ಅಡುಗೆಯ ಆರಂಭದಲ್ಲಿ ಅವುಗಳನ್ನು ಬಿಸಿ ಎಣ್ಣೆಗೆ ಸೇರಿಸಲಾಗುತ್ತದೆ, ಅವುಗಳ ರುಚಿ ಮತ್ತು ಸುವಾಸನೆಯನ್ನು ಬಿಡುಗಡೆ ಮಾಡುತ್ತದೆ, ಭಕ್ಷ್ಯದ ರುಚಿಯನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ. ಅವುಗಳ ಪಾಕಶಾಲೆಯ ಉಪಯೋಗಗಳಲ್ಲದೆ, ಕರಿಬೇವಿನ ಎಲೆಗಳು ಕೆಲವು ಆರೋಗ್ಯ ಪ್ರಯೋಜನಗಳನ್ನು ಹೊಂದಿವೆ ಎಂದು ನಂಬಲಾಗಿದೆ. ಅವು ಉತ್ಕರ್ಷಣ ನಿರೋಧಕಗಳು, ವಿಟಮಿನ್ ಎ, ಬಿ ಮತ್ತು ಸಿ ನಂತಹ ಜೀವಸತ್ವಗಳು ಮತ್ತು ಕ್ಯಾಲ್ಸಿಯಂ, ರಂಜಕ ಮತ್ತು ಕಬ್ಬಿಣದಂತಹ ಖನಿಜಗಳಲ್ಲಿ ಸಮೃದ್ಧವಾಗಿವೆ. ಈ ಎಲೆಗಳು ಜೀರ್ಣಕ್ರಿಯೆಗೆ ಸಹಾಯ ಮಾಡುವುದು, ಕೂದಲಿನ ಆರೋಗ್ಯವನ್ನು ಉತ್ತೇಜಿಸುವುದು ಮತ್ತು ಉರಿಯೂತದ ಪರಿಣಾಮಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಅವುಗಳ ಸಂಭಾವ್ಯ ಔಷಧೀಯ ಗುಣಗಳಿಗೆ ಹೆಸರುವಾಸಿಯಾಗಿದೆ.',
    'Doddapatre' : 'ದೊಡ್ಡಪತ್ರೆಯು ಸುಮಾರು ಮೂವತ್ತರಿಂದ ತೊಂಬತ್ತು ಸೆ.ಮೀ ಎತ್ತರದವರೆಗೆ ಬೆಳೆಯಬಲ್ಲದು, ಇದರ ಎಲೆಗಳು ದೊಡ್ಡ ಮತ್ತು ದಪ್ಪವಾಗಿದ್ದು ಕಡು ಸುವಾಸನೆಯನ್ನು ಹೊಂದಿರುತ್ತವೆ, ದೊಡ್ಡಪತ್ರೆಯ ರಂಬೆಗಳು ಮತ್ತು ಹೂಗಳು ಚಿಕ್ಕದಾಗಿದೆ. ಆಫ್ರಿಕಾ ದೇಶಗಳಲ್ಲಿ ಇದನ್ನು ಪುದೀನಾದ ಬದಲಿಗೆ  ಖಾದ್ಯಗಳಲ್ಲಿ ಬಳಸುತ್ತಾರೆ. ದಕ್ಷಿಣಭಾರತದಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಇದನ್ನು ಜ್ವರ, ಶೀತ, ಕೆಮ್ಮುಗಳಿಗೆ ಮನೆಮದ್ದಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ. ಗಾಯ ಅಥವಾ ಚೇಳು ಕಡಿತವಾದಾಗ ಪ್ರಥಮ ಚಿಕಿತ್ಸೆಯಾಗಿ ಇದರ ಎಲೆಗಳನ್ನು ಜಜ್ಜಿ ಬಳಸಲಾಗುತ್ತದೆ. ದಕ್ಷಿಣ ಕರ್ನಾಟಕದಲ್ಲಿ ದೊಡ್ಡಪತ್ರೆಯ ಚಟ್ನಿ, ತಂಬುಳಿ ಮಾಡಲಾಗುತ್ತದೆ. ಈಗ ಈ ದೊಡ್ಡ ಪತ್ರೆ ಸೊಪ್ಪು ಯಾವೆಲ್ಲಾ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳಿಗೆ ಪರಿಹಾರ ನೀಡುತ್ತದೆ ಎನ್ನುವ ಬಗ್ಗೆ ಮಾಹಿತಿಯನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ ಇಲ್ಲಿದೆ ನೋಡಿ. ಸಾಮಾನ್ಯವಾಗಿ ಆಹಾರ ಸೇವನೆಯಲ್ಲಿ ಬದಲಾವಣೆ, ಹವಾಮಾನದಲ್ಲಿನ ವ್ಯತ್ಯಾಸದಿಂದ ಶ್ವಾಸಕೋಶದಲ್ಲಿ ಕಫ ಕಟ್ಟಿಕೊಳ್ಳುತ್ತದೆ. ಇದರಿಂದ ಶೀತವಾದರೆ ಎಷ್ಟು ದಿನವಾದರೂ ಕಡಿಮೆಯಾಗುವುದಿಲ್ಲ. ಇದಕ್ಕೆ ದೊಡ್ಡ ಪತ್ರೆ ಸೊಪ್ಪು ಉತ್ತಮ ಮನೆಮದ್ದಾಗಿದೆ. ದೊಡ್ಡಪತ್ರೆ ಎಲೆ, ತುಳಸಿ ಎಲೆ ಮತ್ತು ವೀಳ್ಯದೆಲೆಯನ್ನು ಅರೆದು ರಸ ತೆಗೆದು ಅದಕ್ಕೆ ಜೇನುತುಪ್ಪ ಬೆರೆಸಿ ಕುಡಿದರೆ ನೆಗಡಿ, ಕೆಮ್ಮು ದೂರವಾಗುತ್ತದೆ. ಚಿಕ್ಕ ಮಕ್ಕಳಿಗೂ ಕೂಡ ಈ ದೊಡ್ಡ ಪತ್ರೆ ಸೊಪ್ಪನ್ನು ಔಷಧವಾಗಿ ಬಳಸಬಹುದಾಗಿದೆ.',
    'Ekka' : 'ಬಿಳಿ ಎಕ್ಕ ಗಿಡವು ಭಾರತದ ಎಲ್ಲಾ ಪ್ರದೇಶಗಳಲ್ಲಿ ಸಿಗುವಂತಹದ್ದು. ಆದರೆ ಪುರಾತನವಾದ ಗಿಡವು ಸಿಗುವುದು ದುರ್ಲಭವಾಗಿರುವುದು. ಎಕ್ಕ ಗಿಡದಲ್ಲಿ ಗುಲಾಬಿ, ನೀಲಿ ಬಣ್ಣದ ಹೂಗಳಿರುವಂತಹ ಸಸ್ಯಗಳು ಎಲ್ಲಾ ಕಡೆಗಳಲ್ಲಿ ಸಿಗುವುವು ಆದರೆ ಬಿಳಿ ಎಕ್ಕದ ಗಿಡ ಸಿಗುವುದು ವಿರಳ. ಇದನ್ನು ಶ್ವೇತಾರ್ಕವೆಂದೂ ಕರೆಯುತ್ತಾರೆ. ಈ ಗಿಡವು ೬ ರಿಂದ ೭ ಅಡಿ ಎತ್ತರವಾಗಿ,೪ ರಿಂದ ೫ ಅಡಿ ವಿಸ್ತಾರವನ್ನು ಹೊಂದಿರುತ್ತದೆ. ಸುತ್ತಲೂ ಹರಡಿಕೊಂಡಿರುವ ಸಸ್ಯವಿದಾಗಿದೆ. ಇನ್ನೂ ಹೆಚ್ಚು ಹರಡಿರುವ ಸಾಧ್ಯತೆಯೂ ಇದೆ. ಈ ಸಸ್ಯಕ್ಕೆ ಬಲಿಷ್ಠವಾದ ಟೊಂಗೆಗಳಿದ್ದು,ವಟವೃಕ್ಷದ ಎಲೆಗಳಂತೆ ಎಲೆ ಹೊಂದಿರುತ್ತದೆ. ಬಿಳಿ ಹಾಲಿನಂತೆ ಬಣ್ಣ ಹೊಂದಿದ ಹೂಗಳಿದ್ದು,ಬೀಜಗಳು ಅಗಸೇ ಗಿಡದ ಬೀಜಗಳಂತಿರುತ್ತವೆ. ಮೂಲವ್ಯಾಧಿಯು ಉಷ್ಣ ಪ್ರದೇಶದಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಕಂಡು ಬರುವ ರೋಗವಾಗಿರುವುದು. ಮಲಬದ್ಧತೆ ಆಹಾರದೋಷಗಳು ಮೂಲವ್ಯಾಧಿಗೆ ಕಾರಣಗಳಾಗಿವೆ. ಆಯುರ್ವೇದದಲ್ಲಿ ಉತ್ತಮವಾದ ಹಲವು ಚಿಕಿತ್ಸೆಗಳು ಜಾರಿಯಲ್ಲಿವೆ. ಎಕ್ಕದ ಬೇರನ್ನು ತಂದು ತಣ್ಣೀರಿನಲ್ಲಿ ಅರೆದು ಚೇಳು ಕಡಿದವರಿಗೆ ಕುಡಿಸುವುದರಿಂದ ವಿಷದ ಬಾಧೆಯು ನಿವಾರಣೆಯಾಗುವುದು. ಎಕ್ಕದ ಹಾಲು, ಎಲೆ,ಬೇರುಗಳಿಂದ ಹಲವಾರು ರೋಗಗಳ ನಿವಾರಣೆಯಾಗುತ್ತದೆ.',
    'Ganike' : 'ಗಣಿಕೆ ಸೊಪ್ಪು ಕನ್ನಡದಲ್ಲಿ ಗಣಿಕೆ ಅಥವಾ ಕಕ್ಕೆ ಸೊಪ್ಪು, ತಮಿಳಿನಲ್ಲಿ ಮಾನತಕ್ಕಲಿ ಕೀರೈ ಮುಂತಾದ ಅನೇಕ ಪ್ರಾದೇಶಿಕ ಹೆಸರುಗಳಿಂದ ವ್ಯಾಪಕವಾಗಿ ತಿಳಿದಿರುವ ಗಿಡಮೂಲಿಕೆಯಾಗಿದೆ. ಇದು ಔಷಧೀಯ ಮೂಲಿಕೆ ಮತ್ತು ಹೊಟ್ಟೆಯ ಕಾಯಿಲೆಗಳಿಗೆ ತುಂಬಾ ಒಳ್ಳೆಯದು.  ಸಾಮಾನ್ಯವಾಗಿ ಹಸಿರು ಎಲೆಗಳನ್ನು ತಂಬ್ಲಿ ಮಾಡಲು ಬಳಸಲಾಗುತ್ತದೆ ಮತ್ತು ಇದು ಮುಟ್ಟಿನ ಸೆಳೆತ ಮತ್ತು ಹೊಟ್ಟೆಗೆ ಸಂಬಂಧಿಸಿದ ಅಸ್ವಸ್ಥತೆಗಳಿಗೆ ಪರಿಹಾರವಾಗಿದೆ.',
    'Gauva' : 'ಪೈರಸ್ ಕಮ್ಯುನಿಸ್ ಎಂದೂ ಕರೆಯಲ್ಪಡುವ ಪಿಯರ್ ರೋಸೇಸಿ ಕುಟುಂಬದಿಂದ ಬಂದಿದೆ. ಇದನ್ನು ಪ್ರಪಂಚದಾದ್ಯಂತ ಬೆಳೆಯಲಾಗುತ್ತದೆ ಮತ್ತು ಸೇವಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಬೇಸಿಗೆಯ ಕೊನೆಯಲ್ಲಿ ಶರತ್ಕಾಲದ ಮಧ್ಯದವರೆಗೆ ಕೊಯ್ಲು ಮಾಡಲಾಗುತ್ತದೆ. ಪಿಯರ್ ಮರವು ಮಧ್ಯಮ ಗಾತ್ರದಲ್ಲಿದೆ ಮತ್ತು ಏಷ್ಯಾ, ಯುರೋಪ್ ಮತ್ತು ಉತ್ತರ ಆಫ್ರಿಕಾದ ಕರಾವಳಿ ಮತ್ತು ಸೌಮ್ಯವಾದ ಸಮಶೀತೋಷ್ಣ ಪ್ರದೇಶಗಳ ಸ್ಥಳೀಯ ಹಣ್ಣು. ಸೇಬಿನ ನಂತರ ಇದು ವಿಶ್ವದ ಎರಡನೇ ಅತ್ಯಂತ ಪೌಷ್ಟಿಕ ಹಣ್ಣು. ಪೇರಳೆಯು ವಿಟಮಿನ್‌ಗಳು, ಡಯೆಟರಿ ಫೈಬರ್, ಅಮೈನೋ ಆಮ್ಲಗಳು ಮುಂತಾದ ಅನೇಕ ಪೋಷಕಾಂಶಗಳ ಸಮೃದ್ಧ ಮೂಲವಾಗಿದೆ. ಇದು ವಿವಿಧ ಸಂಸ್ಕೃತಿಗಳಲ್ಲಿ ವಿವಿಧ ಹೆಸರುಗಳನ್ನು ಹೊಂದಿದೆ. ಹಿಂದಿಯಲ್ಲಿ, ಇದನ್ನು ನಾಶಪತಿ ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ, ಮತ್ತು ಸಂಸ್ಕೃತದಲ್ಲಿ, ಇದನ್ನು ಅಮೃತಫಲೆ ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ, ಏಕೆಂದರೆ ಇದು ಮಾನವ ದೇಹಕ್ಕೆ ಹೆಚ್ಚು ಪ್ರಯೋಜನಕಾರಿಯಾಗಿದೆ. ಮೂತ್ರಪಿಂಡಗಳಿಗೆ ಪ್ರಯೋಜನಕಾರಿ: ಪೇರಳೆಯು ಅಲ್ಪ ಪ್ರಮಾಣದ ಸೋಡಿಯಂ ಮೌಲ್ಯವನ್ನು ಹೊಂದಿರುವುದರಿಂದ, ಮೂತ್ರಪಿಂಡದ ಕಾಯಿಲೆಗಳನ್ನು ತಡೆಗಟ್ಟಲು ಇದು ಅತ್ಯುತ್ತಮ ಹಣ್ಣಿನ ಆಯ್ಕೆಯಾಗಿದೆ. ಮೂತ್ರಪಿಂಡದ ಕಲ್ಲುಗಳು ಮತ್ತು ಇತರ ಸಂಬಂಧಿತ ಕಾಯಿಲೆಗಳಿಂದ ಬಳಲುತ್ತಿರುವವರು ತಮ್ಮ ದೇಹದಲ್ಲಿ ನೀರು ಮತ್ತು ಸೋಡಿಯಂ ಅನ್ನು ಸಮತೋಲನಗೊಳಿಸುವುದು ಸವಾಲಿನ ಸಂಗತಿಯಾಗಿದೆ. ಪೌಷ್ಟಿಕಾಂಶದ ವಿಷಯ 100 ಗ್ರಾಂಗೆ ಮೊತ್ತ ಶಕ್ತಿ 57 ಕೆ.ಕೆ.ಎಲ್ ಆಹಾರದ ಫೈಬರ್ 3.1 ಗ್ರಾಂ ಪ್ರೋಟೀನ್ 0.36 ಗ್ರಾಂ ಕೊಬ್ಬು 0.14 ಗ್ರಾಂ ಸಕ್ಕರೆ 9.75 ಗ್ರಾಂ ಕಾರ್ಬೋಹೈಡ್ರೇಟ್ 15.23 ಗ್ರಾಂ ಕ್ಯಾಲ್ಸಿಯಂ 9 ಮಿಗ್ರಾಂ ಮೆಗ್ನೀಸಿಯಮ್ 7 ಮಿಗ್ರಾಂ ರಂಜಕ 12 ಮಿಗ್ರಾಂ ಪೊಟ್ಯಾಸಿಯಮ್ 116 ಮಿಗ್ರಾಂ ನೀರು 84 ಗ್ರಾಂ ಕಬ್ಬಿಣ 0.18 ಮಿಗ್ರಾಂ ಕೋಲೀನ್ 5.1 ಮಿಗ್ರಾಂ ವಿಟಮಿನ್ ಸಿ 4.3 ಮಿಗ್ರಾಂ ವಿಟಮಿನ್ ಕೆ 4.4 ಮಿಗ್ರಾಂ ನೀರು 84 ಗ್ರಾಂ ಪಿಯರ್ ಬಗ್ಗೆ ಆಸಕ್ತಿದಾಯಕ ಸಂಗತಿಗಳು ಪ್ರತಿ ಪಿಯರ್‌ಗೆ 100 ಕ್ಯಾಲೋರಿಗಳಿವೆ, ಇದು ಕ್ಯಾಲೋರಿ-ದಟ್ಟವಾದ ಹಣ್ಣಾಗಿದೆ.',
    'Geranium' : 'ಜಿರೇನಿಯಮ್ - ಜಿರೇನಿಯೇಸೀ ಕುಟುಂಬಕ್ಕೆ ಸೇರಿದ ಏಕವಾರ್ಷಿಕ ದ್ವೈವಾರ್ಷಿಕ ಹಾಗೂ ಬಹುವಾರ್ಷಿಕ ಮೂಲಿಕೆ ಸಸ್ಯ. ಅಲಂಕಾರ ಸಸ್ಯವೆಂದು ಪ್ರಸಿದ್ಧವಾಗಿದೆ. ಇದನ್ನು ಅಂಚುಸಸ್ಯ, ಕಲ್ಲೇರಿ ಸಸ್ಯವಾಗಿ ಬೆಳೆಸಲಾಗುತ್ತದೆ. ಜಿರೇನಿಯಮ್ ಎಂಬ ಹೆಸರು ಇನ್ನೊಂದು ಸುಪ್ರಸಿದ್ಧ ಅಲಂಕಾರ ಸಸ್ಯವಾದ ಪೆಲಾರ್ಗೋನೀಯಮಿಗೂ ಅನ್ವಯವಾಗುತ್ತದೆ. ಇದು 8 - 45 ಸೆಂ.ಮೀ. ಎತ್ತರಕ್ಕೆ ಬೆಳೆಯುವ ಪುಟ್ಟಗಿಡ. ಎಲೆಗಳು ಸರಳ; ಪರ್ಯಾಯ ಇಲ್ಲವೆ ಅಭಿಮುಖ ಮಾದರಿಯಲ್ಲಿ ಜೋಡಣೆಗೊಂಡಿವೆ. ಎಲೆಯ ಅಲಗು ಹಸ್ತಾಕೃತಿಯ ಹಾಲೆಗಳಾಗಿ ವಿಭಾಗಗೊಂಡಿದೆ. ಹೂಗಳು ಕ್ರಮಬದ್ಧ ಹಾಗೂ ಸಮಾಂಗತ್ವವುಳ್ಳವು, ಮಧ್ಯಾರಂಭಿ ಇಲ್ಲವೆ ಸಿನ್‍ಸಿನಸ್ ಮಾದರಿಯ ಗೊಂಚಲುಗಳಲ್ಲಿ ಸಮಾವೇಶಗೊಂಡಿವೆ. ಪ್ರತಿ ಹೂವಿನಲ್ಲಿ 5 ಬಿಡಿ ಪುಷ್ಪ ಪತ್ರಗಳು, 5 ಬಿಡಿ ದಳಗಳು, 10 ಕೇಸರಗಳು, 5 ಕಾರ್ಪೆಲುಗಳುಳ್ಳ ಉಚ್ಚಸ್ಥಾನದ ಅಂಡಾಶಯ ಇವೆ. ಉದ್ದವಾದ ಶಲಾಕೆಯೂ ಅದರ ತುದಿಯಲ್ಲಿ 5 ಕವಲುಗಳ ಶಲಾಕಾಗ್ರವೂ ಉಂಟು. ಫಲ ಸಂಪುಟ ಮಾದರಿಯದು: ಸಂಪೂರ್ಣ ಬಲಿತ ಅನಂತರ ಒಣಗಿ ಒಡೆಯುತ್ತದೆ. ಹೀಗೆ ಕಾರ್ಪೆಲುಗಳು ಮೇಲಕ್ಕೆದ್ದುಕೊಳ್ಳುತ್ತವೆ.',
    'Henna' : 'ಗೋರಂಟಿ ಲಿತ್ರೇಸೀ ಕುಟುಂಬಕ್ಕೆ ಸೇರಿದ ಒಂದು ಸಸ್ಯ. ಮದರಂಗಿ ಪರ್ಯಾಯನಾಮ. ಇದರ ಶಾಸ್ತ್ರೀಯ ಹೆಸರು ಲಾಸೋನಿಯ ಇನರ್ಮಿಸ್. ಇಂಗ್ಲಿಷಿನಲ್ಲಿ ಇದನ್ನು ಹೆನ ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ. ಇದು ಉತ್ತರ ಆಫ್ರಿಕ ಹಾಗೂ ನೈರುತ್ಯ ಏಷ್ಯದ ಮೂಲವಾಸಿ. ಇದನ್ನು ಅಲಂಕಾರಕ್ಕಾಗಿಯೂ ಇದರಿಂದ ಪಡೆಯಲಾಗುವ ಬಣ್ಣಕ್ಕಾಗಿಯೂ ಬೆಳೆಸಲಾಗುತ್ತದೆ.ಹೆಣ್ಣು ಮಕ್ಕಳು ಇದರ ಎಲೆಗಳನ್ನು ನೀರಿನಲ್ಲಿ ಅರೆದು ಕೈ ಕಾಲುಗಳಿಗೆ ಚಿತ್ರಾಕಾರವಾಗಿ ಹಚ್ಚುವರು. ತೊಳೆದ ಮೇಲೆ ಕೆಂಪು ರಂಗೇರಿ ಹೆಚ್ಚು ಸೌಂದರ್ಯವನ್ನು ಕೊಡುವುದು, ಹಿರಿಯರು ತಲೆ ಮತ್ತು ಗಡ್ಡಗಳಿಗೆ ಹಚ್ಚಿ ಬಿಳಿಕೂದಲು ಕೆಂಪಾಗುವಂತೆ ಮಾಡುತ್ತಾರೆ. ಮದುವೆಗಳಲ್ಲಿ ಹೆಣ್ಣಿಗೆ ಮೆಹಂದಿ ಹಚ್ಚುವ ಸಂಪ್ರದಾಯವಿದೆ. ಗೋರಂಟಿ ಎಲೆಗಳಿಗೆ ಔಷಧೀಯ ಗುಣಗಳಿವೆ. ಕಷಾಯದ ರೂಪದಲ್ಲಿ ಇಲ್ಲವೆ ಸರಿಯ ರೂಪದಲ್ಲಿ ಇವನ್ನು ಹುಣ್ಣು, ತರಚು ಹಾಗೂ ಸುಟ್ಟಗಾಯಗಳು ಮತ್ತು ಕೆಲವು ಚರ್ಮರೋಗಗಳಿಗೆ ಬಳಸುತ್ತಾರೆ. ಕಷಾಯ ಗಂಟಲುನೋವಿಗೆ ಒಳ್ಳೆಯ ಮದ್ದು. ಗೋರಂಟಿಯ ಹೂವನ್ನು ಆವಿ ಅಸವೀಕರಣಕ್ಕೊಳಪಡಿಸಿ ಒಂದು ಬಗೆಯ ಪರಿಮಳಯುಕ್ತ ಚಂಚಲ ತೈಲವನ್ನು ಪಡೆಯಬಹುದು. ಇದಕ್ಕೆ ಮೆಹಂದಿ ಎಣ್ಣೆ ಎಂದು ಹೆಸರು. ಇದನ್ನು ಸುಗಂಧ ದ್ರವ್ಯಗಳ ತಯಾರಿಕೆಯಲ್ಲಿ ಬಳಸುತ್ತಾರೆ. ಗೋರಂಟಿಯ ಚೌಬೀನೆಯನ್ನು ಉಪಕರಣಗಳ ಹಿಡಿ, ಗೂಟ ಮುಂತಾದವುಗಳ ತಯಾರಿಕೆಗೆ ಉಪಯೋಗಿಸುತ್ತಾರೆ. ',
    'Hibiscus' : 'ಹೂವಿನ ಗಿಡವಾಗಿರುವ ದಾಸವಾಳವನ್ನು ನಾವು ಉಷ್ಣವಲಯ ಹಾಗೂ ಉಪಉಷ್ಣವಲಯದ ಪ್ರದೇಶಗಳಲ್ಲಿ ಕಾಣಬಹುದಾಗಿದೆ. ದಾಸವಾಳವನ್ನು "ಮಾರ್ಷ್ ಮ್ಯಾಲೋ" ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ. ದಾಸವಾಳದ ಎಲೆಗಳು ಭಾರತದಲ್ಲಿ ಸಾಮಾನ್ಯ ಹಾಗೂ ಇದನ್ನು ಹಲವಾರು ರೋಗಗಳಿಗೆ ಚಿಕಿತ್ಸೆಯಾಗಿ ಆಯುರ್ವೇದದಲ್ಲಿ ಸಾವಿರಾರು ವರ್ಷಗಳಿಂದ ಬಳಸಲಾಗುತ್ತಿದೆ. ಜಗತ್ತಿನಾದ್ಯಂತ ಹೆಚ್ಚಿನ ಜನರು ದಾಸವಾಳದ ಎಲೆಗಳನ್ನು ಬಿಸಿ ಅಥವಾ ತಂಪು ಚಹಾದಲ್ಲಿ ಬಳಸುತ್ತಾರೆ. ಇದು ಆರೋಗ್ಯಕ್ಕೆ ತುಂಬಾ ಲಾಭಕಾರಿ. ದಾಸವಾಳದ ಎಲೆಗಳ ಇತರ ಆರೋಗ್ಯ ಲಾಭಗಳೆಂದರೆ ಈ ಎಲೆಗಳನ್ನು ರಕ್ತದೊತ್ತಡ ಮತ್ತು ಅಧಿಕ ರಕ್ತದೊತ್ತಡದಿಂದ ಬಳಲುವವರಿಗೆ ಚಿಕಿತ್ಸೆಗೆ ಬಳಸಬಹುದು. ದಾಸವಾಳದ ಎಲೆಗಳು ಕ್ಯಾನ್ಸರ್ ವಿರುದ್ಧ ಹೋರಾಡುವ ಗುಣಗಳನ್ನು ಹೊಂದಿರುವ ಕಾರಣ ಈ ಎಲೆಗಳನ್ನು ಬಿಸಿ ನೀರಿನಲ್ಲಿ ಹಾಕಿ ಸೇವಿಸಬೇಕು. ಕ್ಯಾನ್ಸರ್ ನಿಂದ ಆಗಿರುವಂತಹ ಗಾಯಕ್ಕೆ ಇದರ ಪೇಸ್ಟ್ ಮಾಡಿ ಹಚ್ಚಬಹುದು.',
    'Honge' : 'ಹೊಂಗೆ ಮರ ಬಹಳ ಹಿಂದಿನ ಕಾಲದಿಂದಲೂ ಭಾರತೀಯರಿಗೆ ಚಿರಪರಿಚಿತವಿರುವ ಮರ. ಭಾರತದೆಲ್ಲೆಡೆಯೂ ಈ ಮರವನ್ನು ಬೆಳೆಸುತ್ತಾರೆ. ರೈತರು ಗದ್ದೆ ಮತ್ತು ಹೊಲಗಳ ಬದಿಯಲ್ಲಿ ಈ ಮರವನ್ನು ಬೆಳೆಸುತ್ತಾರೆ. ನೀರಿನ ನಾಲೆಗಳ ಬದಿಯಲ್ಲಿ ಸ್ವಾಭಾವಿಕವಾಗಿಯೇ ಬೆಳೆಯುತ್ತದೆ. ಇದು ನಿತ್ಯಹಸುರಿನ ಮರ. ಕರಾವಳಿ ಪ್ರದೇಶಗಳಲ್ಲಿಯೂ ಬೆಳೆಯುತ್ತದೆ. ಒಳನಾಡಿನಲ್ಲಿ ತೋಪುಗಳಲ್ಲಿ ಸಾಲು ಮರಗಳಾಗಿ ಇದನ್ನು ವಿಶೇಷವಾಗಿ ಬೆಳೆಸುತ್ತಾರೆ. ಬರಡು ಪ್ರದೇಶಗಳಲ್ಲಿಯೂ ಚೆನ್ನಾಗಿ ಬೆಳೆಯುತ್ತದೆ. ಅಲ್ಲಲ್ಲಿ ತೋಪುಗಳಲ್ಲಿ ಬೆಳೆಯುವುದುಂಟು. ಕುಳ್ಳು ಕಾಂಡದ ಇದು ಹರಡಿ ವಿಸ್ತಾರವಾಗಿ ಬೆಳೆಯುವುದು. ಇದರ ವೈಜ್ಞಾನಿಕ ಹೆಸರು ಪೊಂಗಾಮಿಯಾ ಪಿನ್ನಾಟ. ಇದು ಲೆಗ್ಯುಮಿನೋಸೀ ಸಸ್ಯಕುಟುಂಬಕ್ಕೆ ಸೇರಿದೆ. ಇದನ್ನು ಮಧುಮೇಹ ನಿವಾರಣೆಯಲ್ಲಿ ಬಳಸುತ್ತಾರೆ. ಹೇನು ಕೆರೆ, ಮೀಸೆ,ಗಡ್ಡ ಮತ್ತು ತಲೆಯಲ್ಲಿ ಕೂದಲಿನ ಉದುರಿವಿಕೆಯನ್ನು ತಡೆಯಲು, ಒಣಗಿದ ಹೊಂಗೆ ಬೀಜಗಳನ್ನು ನೀರಿನಲ್ಲಿ ತೇದು ಗಂಧವನ್ನು ಕೂದಲು ಉದುರುವ ಕಡೆ ಹಚ್ಚುವುದು. ತಲೆನೋವಿನಲ್ಲಿ ಉಪಯೋಗಿಸುತ್ತಾರೆ. ಚರ್ಮ ಕಾಯಿಲೆಯಲ್ಲಿ ಅದರ ಬೀಜದ ಎಣ್ಣೆಯನ್ನು ಹಾಗೂ ಎಲೆಯ ಕಷಾಯವನ್ನು ಬಳಸುತ್ತಾರೆ. ಕೈಕಾಲು ಮತ್ತು ಕೀಲು ನೋವಿಗೆ ಇದರ ಎಣ್ಣೆಯನ್ನು ಬಳಸುತ್ತಾರೆ',
    'Insulin' : 'ಕಾಸ್ಟಸ್ ಇಗ್ನಿಯಸ್ ಅನ್ನು ಇನ್ಸುಲಿನ್ ಸಸ್ಯ ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ ಏಕೆಂದರೆ ಇದು ಮಧುಮೇಹ ಹೊಂದಿರುವ ಕೆಲವು ಜನರಿಗೆ ಗ್ಲೂಕೋಸ್ ಮಟ್ಟವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಈ ಸಸ್ಯವು ತಲೆತಿರುಗುವಿಕೆ ಮತ್ತು ಹೊಟ್ಟೆಯ ಸಮಸ್ಯೆಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಅಡ್ಡ ಪರಿಣಾಮಗಳನ್ನು ಉಂಟುಮಾಡಬಹುದು.ಗಂಭೀರ ಕಾಯಿಲೆಗಳಿಗೆ ಚಿಕಿತ್ಸೆ ನೀಡುವ ಹಲವು ಗಿಡಮೂಲಿಕೆಗಳನ್ನು ನಮ್ಮ ಆಯುರ್ವೇದದಲ್ಲಿ ಉಲ್ಲೇಖಿಸಲಾಗಿದೆ. ಅವುಗಳಲ್ಲಿ ಕಾಕ್ಟಸ್ ಇಗ್ನಸ್ ಕೂಡ ಒಂದು. ಕ್ಯಾಕ್ಟಸ್ ಇಗ್ನಸ್ ದೇಹದಲ್ಲಿ ಸಕ್ಕರೆಯನ್ನು ನಿಯಂತ್ರಿಸುವ ಮತ್ತು ಮಧುಮೇಹದಲ್ಲಿ ಪ್ರಯೋಜನಕಾರಿ ಸಸ್ಯವಾಗಿದೆ. ಕ್ಯಾಕ್ಟಸ್ ಇಗ್ನಸ್ ಇನ್ಸುಲಿನ್ ನಂತೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಇದನ್ನು ಇನ್ಸುಲಿನ್ ಸಸ್ಯ ಎಂದೂ ಕೂಡ ಕರೆಯುತ್ತಾರೆ. ಈ ಇನ್ಸುಲಿನ್‌ ಗಿಡದಲ್ಲಿ ಹೇರಳವಾದ ಆಂಟಿ ಆಕ್ಸಿಡೆಂಟ್‌, ಪ್ರೋಟೀನ್‌ ಮತ್ತು ಕಬ್ಬಿಣಾಂಶದ ಗುಣಗಳಿವೆ ಎಂದು ಹೇಳಲಾಗುತ್ತದೆ. ಈ ಗಿಡದಲ್ಲಿ ಸಕ್ಕರೆ ಮಟ್ಟವನ್ನು ಕಡಿಮೆ ಮಾಡುವ ರಾಸಾಯನಿಕ ಗುಣಗಳಿದೆ ಎಂದು ಹೇಳಲಾಗುತ್ತದೆ.',
    'Jasmine' : 'ಜಾಸ್ಮಿನ್ ಅನ್ನು ಹೂವುಗಳ ರಾಣಿ ಎಂದು ಪರಿಗಣಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಇದನ್ನು "ಬೆಲ್ಲೆ ಆಫ್ ಇಂಡಿಯಾ" ಅಥವಾ "ಸುಗಂಧ ರಾಣಿ" ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ ಏಕೆಂದರೆ ಇದು ಶಮನಗೊಳಿಸಲು ಮತ್ತು ರಿಫ್ರೆಶ್ ಮಾಡಲು ಸೊಗಸಾದ ಪರಿಮಳವನ್ನು ಹೊಂದಿರುತ್ತದೆ. ಭಾರತದ ವಿವಿಧ ಭಾಗಗಳಲ್ಲಿ ಇದನ್ನು ವಿವಿಧ ಹೆಸರುಗಳಿಂದ ಕರೆಯಲಾಗುತ್ತದೆ- ಮೊಗ್ರಾ , ಮೋಟಿಯಾ , ಚಮೇಲಿ , ಮಲ್ಲಿ ಪುವ್ವು, ಜಾತಿ, ಮುಲ್ಲಾ, ಮಲ್ಲಿಗೆ, ಜೂಹಿ, ಮೊಗ್ರಾ ಅಥವಾ ತೋಪಿನಲ್ಲಿ ಬೆಳದಿಂಗಳು. ಮಲ್ಲಿಗೆಯಲ್ಲಿ 300 ವಿಧಗಳಿವೆ ಎಂದು ವರದಿಯಾಗಿದೆ. ಮಲ್ಲಿಗೆಯು ಏಷ್ಯಾದಿಂದ ಯುರೋಪ್‌ಗೆ ಸಮುದ್ರಗಳನ್ನು ದಾಟಿ, ಮೆಡಿಟರೇನಿಯನ್ ಸಮುದ್ರದ ಉದ್ದಕ್ಕೂ ಮೊದಲು ಇಳಿದು , ಗ್ರೀಸ್ ಮತ್ತು ಟರ್ಕಿಯನ್ನು ವಶಪಡಿಸಿಕೊಂಡು, ಸ್ಪೇನ್ , ನಂತರ ಫ್ರಾನ್ಸ್ ಮತ್ತು ಇಟಲಿಯ ಮೂಲಕ ಪಶ್ಚಿಮ ಯುರೋಪ್ ಅನ್ನು ತಲುಪಿತು ಮತ್ತು ಅಂತಿಮವಾಗಿ 17 ನೇ ಶತಮಾನದ ಉತ್ತರಾರ್ಧದಲ್ಲಿ ಇಂಗ್ಲೆಂಡ್‌ನಲ್ಲಿ ಇಳಿಯುತ್ತದೆ ಎಂದು ಹೇಳಲಾಗಿದೆ. ಹೂವುಗಳನ್ನು ಹೂಮಾಲೆಗಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ, ವಿಶೇಷವಾಗಿ ಮದುವೆಗಳು ಮತ್ತು ಇತರ ಮಂಗಳಕರ ಸಂದರ್ಭಗಳಲ್ಲಿ ಮತ್ತು ದೇವಾಲಯಗಳ ದೇವತೆಗಳ ಪೂಜೆಗಾಗಿ ಹೂಮಾಲೆಗಳನ್ನು ತಯಾರಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ. ಜಾಸ್ಮಿನ್ ಅನ್ನು ತಮ್ಮ ಹೂವುಗಳಿಗಾಗಿ ವ್ಯಾಪಕವಾಗಿ ಬೆಳೆಸಲಾಗುತ್ತದೆ, ತೋಟದಲ್ಲಿ, ಮನೆ ಗಿಡಗಳಾಗಿ ಮತ್ತು ಕತ್ತರಿಸಿದ ಹೂವುಗಳಾಗಿ ಆನಂದಿಸಲಾಗುತ್ತದೆ. ಹೂವುಗಳನ್ನು ದಕ್ಷಿಣ ಮತ್ತು ಆಗ್ನೇಯ ಏಷ್ಯಾದಲ್ಲಿ ಮಹಿಳೆಯರು ತಮ್ಮ ಕೂದಲಿನಲ್ಲಿ ಧರಿಸುತ್ತಾರೆ.ಅವುಗಳನ್ನು ರಫ್ತು ಮಾಡಲಾಗುತ್ತದೆ ಮತ್ತು ಹೀಗಾಗಿ ರೈತರಿಗೆ ಹೆಚ್ಚು ಲಾಭದಾಯಕವಾಗಿದೆ. ಇದರ ಔಷಧೀಯ ಉಪಯೋಗಗಳು ಖಿನ್ನತೆ-ನಿರೋಧಕ, ಆಂಟಿ ಸೆಪ್ಟಿಕ್, ಆಂಟಿ ಸ್ಪಾಸ್ಮೊಡಿಕ್, ಕಾಮೋತ್ತೇಜಕ, ನಿದ್ರಾಜನಕ ಮತ್ತು ಗರ್ಭಾಶಯ. ',
    'Lemon' : 'ನಿಂಬೆಯು ಸದಾ ಹಸಿರಾಗಿರುವ ಒಂದು ಚಿಕ್ಕ ಮರ, ರೂಟೇಸೀ ಕುಟುಂಬಕ್ಕೆ ಸೇರಿದ ಜನಪ್ರಿಯ ಫಲವೃಕ್ಷ (ಲೈಮ್). ಇದಕ್ಕೆ ನಿಂಬೆಗಿಡ ಎಂದು ಕೂಡ ಕರೆಯಲಾಗುತ್ತದೆ. ಬಾಳೆ ಮತ್ತು ಮಾವಿನ ನಂತರ ಅತಿ ಹೆಚ್ಚು ಬೇಡಿಕೆ ಇರುವ ಹಣ್ಣಿನ ಬೆಳೆಯೇ ನಿಂಬೆ. ತೋಟಗಾರಿಕೆ ಬೆಳೆಯಾಗಿರುವ ಇದು ಕಡಿಮೆ ಫಲವತ್ತತೆಯ ಮಣ್ಣಿನಲ್ಲಿ ಚೆನ್ನಾಗಿ ಬೆಳೆಯುವ ಗುಣ ಹೊಂದಿದೆ. ಇದು ವಿಟಾಮಿನ್ ಸಿ ಅನ್ನು ಯಥೇಚ್ಛವಾಗಿ ಹೊಂದಿದೆ. ಹುಳಿ ರುಚಿಯನ್ನು ಹೊಂದಿರುವ ನಿಂಬೆ ಹಣ್ಣು ನಮ್ಮ ಹೃದಯಕ್ಕೆ ಆರೋಗ್ಯವನ್ನು ಕಾಪಾಡುತ್ತದೆ. ನಮ್ಮ ದೇಹದಲ್ಲಿನ ಕೊಲೆಸ್ಟ್ರಾಲ್ ಮತ್ತು ರಕ್ತದೊತ್ತಡದ ಮಟ್ಟವನ್ನು ಕಡಿಮೆ ಮಾಡುವ ಮೂಲಕ ಹೃದಯವನ್ನು ಆರೋಗ್ಯವಾಗಿಡುವಲ್ಲಿ ನಿಂಬೆ ಪ್ರಮುಖ ಪಾತ್ರ ವಹಿಸುತ್ತದೆ. ನಿಂಬೆಯಲ್ಲಿರುವ ಸಿಟ್ರಿಕ್ ಆಮ್ಲವು ಹೃದಯ ಸಂಬಂಧಿ ಎಲ್ಲಾ ಸಮಸ್ಯೆಗಳನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ನಿಂಬೆರಸವನ್ನು ಪ್ರತಿನಿತ್ಯ ಕುಡಿದರೆ ಕಿಡ್ನಿ ಸ್ಟೋನ್ ಆಗುವ ಸಾಧ್ಯತೆ ಇರುವುದಿಲ್ಲ. ನಿಂಬೆಹಣ್ಣನ್ನು ಸೇವಿಸುವುದರಿಂದ ನಮ್ಮ ಮೂತ್ರದ ಪ್ರಮಾಣ ಮತ್ತು ಪಿಹೆಚ್ ಹೆಚ್ಚಾಗುತ್ತದೆ. ಅಲ್ಲದೇ ಕಿಡ್ನಿ ಸ್ಟೋನ್ ಸಾಧ್ಯತೆಯನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ. ನಿಂಬೆ ರಸವು ಕೇವಲ ರುಚಿಕರವಾದ ಪಾನೀಯವಲ್ಲ. ಆದರೆ ನಿಮ್ಮ ಮೂತ್ರಪಿಂಡಗಳನ್ನು ರಕ್ಷಿಸುವ ಅಸ್ತ್ರವಾಗಿದೆ ಎಂಬುವುದನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ.ವುದನ್ನು ತಡೆಯುತ್ತದೆ ಮತ್ತು ತೂಕ ಹೆಚ್ಚಾಗುಗುವುದನ್ನು ತಡೆಯುತ್ತದೆ.',
    'Lemon_grass' : 'ಲೆಮನ್ ಗ್ರಾಸ್(Lemongrass) ಎಂದು ಕರೆಯಲ್ಪಡುವ ಮಜ್ಜಿಗೆಹುಲ್ಲು ಪೊಸೇಯ್ ಅಥವಾ ಗ್ರ್ಯಾಮೈನೆ ಹುಲ್ಲುಗಳ ಕುಟುಂಬಕ್ಕೆ ಸೇರಿದ ಸಸ್ಯವಾಗಿದೆ. ಹೂಬಿಡುವ ಸಸ್ಯಗಳ ಪ್ರಭೇದಕ್ಕೆ ಸೇರಿದ ಈ ಸಸ್ಯವು ಏಷ್ಯಾ, ಆಫ್ರಿಕಾ, ಆಸ್ಟ್ರೇಲಿಯಾ ಹಾಗೂ ದ್ವೀಪ ಪ್ರದೇಶಗಳಲ್ಲಿ ಹೆಚ್ಚಾಗಿ ಕಾಣಸಿಗುತ್ತದೆ. ಸಸ್ಯವು ಸುಗಂಧ ತೈಲವನ್ನು ಹೊಂದಿರುವುದರಿಂದ ನಿಂಬೆಹಣ್ಣಿನ ವಾಸನೆಯನ್ನು ಹೊರಹೊಮ್ಮಿಸುತ್ತದೆ. ಈ ಸಲುವಾಗಿ ಇದನ್ನು "ನಿಂಬೆ ಹುಲ್ಲು" ಅಥವಾ "ಎಣ್ಣೆ ಹುಲ್ಲು" ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ. ಚಹಾ ತಯಾರಿಸಲು ನಿಂಬೆಹುಲ್ಲನ್ನು ಹಾಕಿ ಕುದಿಸಿ ತಯಾರಿಸುವುದರಿಂದ ಜೀರ್ಣಶಕ್ತಿ ಹೆಚ್ಚಾಗುವುದರೊಂದಿಗೆ ನೆಗಡಿ, ಕೆಮ್ಮುಗಳಿಗೂ ಉತ್ತಮ ಔಷಧಿ.ಮಕ್ಕಳಲ್ಲಿ ಜ್ವರ ಇರುವಾಗ ನಿಂಬೆಹುಲ್ಲು ಹಾಕಿ ತಯಾರಿಸಿದ ಕಷಾಯಕ್ಕೆ 1/4 ಚಮಚ ಶುಂಠಿ ರಸ ಮತ್ತು ಬೆಲ್ಲ ಬೆರೆಸಿ ಕುಡಿಸಬೇಕು. ಹೊಟ್ಟೆನೋವು ಮತ್ತು ವಾಂತಿಯಾಗುತ್ತಿದ್ದಲ್ಲಿ ನಿಂಬೆಹುಲ್ಲಿನಿಂದ ತಯಾರಿಸಿದ ತೈಲವನ್ನು ಅರ್ಧ ಲೋಟ ನೀರಿಗೆ ಮೂರರಿಂದ ಆರು ಹನಿ ತೈಲ ಹಾಕಿ ಸಕ್ಕರೆ ಬೆರೆಸಿ ಕುಡಿಯಬೇಕು.',
    'Mango' : 'ಮಾವು ಉತ್ತರ ಆಮ್ರಾ(ಮ್ಯಾಂಗಿಫೆರ ಇಂಡಿಕ) ಉಷ್ಣವಲಯದಲ್ಲಿ ಪ್ರಪಂಚದೆಲ್ಲೆಡೆ ವ್ಯಾಪಕವಾಗಿ ಕಂಡು ಬರುವ ಮರ. ಇದರ ದಾರುವಿಗಿಂತ ಹಣ್ಣೇ ಪ್ರಸಿದ್ಧ. ಇದರ 30 ಕ್ಕಿಂತಲೂ ಹೆಚ್ಚು ತಳಿಗಳು ಪ್ರಚಲಿತವಿದೆ. ಇದು ಸುಮಾರು 4೦೦೦ ವರ್ಷಗಳಿಂದಲೂ ಭಾರತದ ವ್ಯವಸಾಯದಲ್ಲಿದ್ದು, ಸುಮಾರು 17 ಮತ್ತು 18ನೇ ಶತಮಾನದಲ್ಲಿ ಯುರೋಪ್‍ನ ಪ್ರವಾಸಿಗರು ಇದನ್ನು ಪಶ್ಚಿಮದ ಉಷ್ಣವಲಯ ದೇಶಗಳಲ್ಲಿ ಪ್ರಸರಿಸಿದರು. ಮಾವಿನ ಹಣ್ಣು ಸವಿಯಾದದ್ದು ಮಾತ್ರವಲ್ಲ, ಅದರ ವೈದ್ಯಕೀಯ ಉಪಯೋಗಗಳಿಂದಲೂ ವಿಶ್ವದೆಲ್ಲೆಡೆ ಜನಪ್ರಿಯವಾಗಿದೆ. ಕೆಲವು ತಳಿಗಳು ಪಾನೀಯ ತಯಾರಿಕೆಗೆ ಸೂಕ್ತವಾಗಿದ್ದು, ಕಾಡು ಮಾವಿನ ಜಾತಿಗಳಲ್ಲಿ ಅಪ್ಪೆ ಮತ್ತು ಉಪ್ಪಿನಕಾಯಿ ತಯಾರಿಕೆಗೆ ಬಳಸುತ್ತಾರೆ. ಎಳೆಯ ಮತ್ತು ಪಕ್ವವಾಗದ ಹಣ್ಣುಗಳನ್ನು ಉಪ್ಪಿನಕಾಯಿ, ಚಟ್ನಿ ಮುಂತಾದ ವಿವಿಧ ಆಹಾರಗಳೊಂದಿಗೆ ಸೇವಿಸುತ್ತಾರೆ. ಪಕ್ವ ಹಣ್ಣುಗಳನ್ನು ರಸ, ಜಾಮ್, ಜೆಲ್ಲಿ, ಮುರಬ್ಬ, ಮತ್ತು ಮಾವಿನಹಪ್ಪಳ (ಆಮ್ ಪಾಪಡ್) ಇತ್ಯಾದಿ ರೂಪಗಳಲ್ಲಿ ಬಳಸುತ್ತಾರೆ. ಮಾವಿನ ಎಳೆಯ ಚಿಗುರನ್ನು ಜಾವಾ ಮತ್ತು ಫಿಲಿಪೀನ್ಸ್ ದೇಶಗಳಲ್ಲಿ ತರಕಾರಿಯಾಗಿ ಬಳಸುತ್ತಾರೆ. ಎಲೆತೊಪ್ಪಲು ದನಗಳಿಗೆ ಮೇವು ಆಗಿ ಬಳಕೆಯಾಗುತ್ತದೆ. ಸುಟ್ಟ ಮಾವಿನ ಎಲೆಗಳ ಬೂದಿಯನ್ನು ಸುಟ್ಟಗಾಯಗಳಿಗೆ ಬಳಸಿದರೆ ವಾಸಿಯಾಗುತ್ತದೆ. ಮಾವಿನ ಒಣಗಿಸಿದ ಹೂಗಳು ಅತಿಸಾರ ಮತ್ತು ಆಮಶಂಕೆಗಳ ಚಿಕಿತ್ಸೆಗೆ ಸಹಾಯಕವಾಗಿದೆ. ತೊಗಟೆಯಲ್ಲಿರುವ ಟ್ಯಾನಿನ್ ಚರ್ಮದ ಹದಗೊಳಿಸಲು ಮತ್ತು ಪ್ರತಿಬಂಧಕವಾಗಿ ಉಪಯೋಗಿಸುತ್ತಾರೆ. ತೊಗಟೆಯಿಂದ ಪಡೆಯುವ ರಸವನ್ನು ಹತ್ತಿ, ರೇಷ್ಮೆ ಮತ್ತು ಉಣ್ಣೆ ಬಟ್ಟೆಗಳಿಗೆ ಪಾಸೆ ಬಣ್ಣ ನೀಡಲು ಬಳಸುತ್ತಾರೆ. ಮಾವಿನ ಮರದಿಂದ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಗೋಂದು ಲಭ್ಯವಿದೆ.',
    'Mint' : 'ಆಯುರ್ವೇದ ಮತ್ತು ಮನೆ ಮದ್ದಿನಲ್ಲಿ ಪುದೀನ ಎಲೆಯನ್ನು ವಿಶೇಷವಾಗಿ ಬಳಸಲಾಗುವುದು. ಇದರಲ್ಲಿ ಇರುವ ಔಷಧೀಯ ಗುಣಗಳು ಸಾಕಷ್ಟು ಅನಾರೋಗ್ಯ ಸಮಸ್ಯೆಗಳನ್ನು ನಿವಾರಿಸುತ್ತವೆ. ವಿಟಮಿನ್ ಎ, ವಿಟಮಿನ್ ಸಿ ಮತ್ತು ವಿಟಮಿನ್ ಬಿ ಕಾಂಪ್ಲೆಕ್ಸ್ ಅನ್ನು ಹೊಂದಿರುವುದು. ಪುದೀನದಲ್ಲಿ ಉತ್ಕರ್ಷಣ ನಿರೋಧಕಗಳು, ಮೆಂಥಾಲ್ ಮತ್ತು ಫೈಟೊನ್ಯೂಟ್ರಿಯಂಟ್‍ಗಳಿವೆ. ಇವು ಕಿಣ್ವಗಳಿಗೆ ಆಹಾರವನ್ನು ಜೀರ್ಣಿಸಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ. ಪುದೀನದಲ್ಲಿ ಇರುವ ಸಾರಭೂತ ತೈಲಗಳು ಬಲವಾದ ಆಂಟಿಬ್ಯಾಕ್ಟೀರಿಯಾ ಮತ್ತು ನಂಜು ನಿರೋಧಕ ಪರಿಣಾಮಗಳನ್ನು ಹೊಂದಿರುತ್ತವೆ. ಅವು ಹೊಟ್ಟೆಯ ಸೆಳೆತವನ್ನು ಶಾಂತಗೊಳಿಸುತ್ತದೆ. ಆಮ್ಲೀಯತೆ ಮತ್ತು ವಾಯುವನ್ನು ಹಿಡಿತದಲ್ಲಿ ಇಡಲು ಸಹಾಯ ಮಾಡುವುದು. ನಿಯಮಿತವಾಗಿ ಪುದೀನ ರಸ ಅಥವಾ ಪುದೀನ ಆಹಾರ ಪದಾರ್ಥಗಳನ್ನು ಸೇವಿಸುವುದರಿಂದ ಎದೆಯ ದಟ್ಟಣೆ ಕಡಿಮೆಯಾಗುತ್ತದೆ. ಪುದೀನದಲ್ಲಿ ಇರುವ ಮೆಂಥಾಲ್ ಡಿಕೊಂಗಸ್ಟೆಂಟ್ ಆಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ. ಇದು ಶ್ವಾಸಕೋಶದಲ್ಲಿ ಸಂಗ್ರಹಿಸಿದ ಲೋಳೆಯನ್ನು ಸಡಿಲಗೊಳಿಸಲು ಸಹಾಯ ಮಡುತ್ತದೆ. ಮೂಗಿನಲ್ಲಿ ಕಟ್ಟಿಕೊಂಡ ಪೊರೆಗಳನ್ನು ಕುಗ್ಗಿಸಿ ಸುಲಭವಾಗಿ ಉಸಿರಾಡಲು ಸಹಾಯ ಗುವಂತೆ ಮಾಡುವುದು. ಪುದೀನವನ್ನು ಮಿತಿ ಮೀರಿ ಸೇವಿಸಬಾರದು. ಮಿತವಾಗಿ ಬಳಸಿದಾಗ ಸಮಸ್ಯೆಯನ್ನು ಆರೋಗ್ಯಕರ ರೀತಿಯಲ್ಲಿ ನಿಯಂತ್ರಣದಲ್ಲಿ ಇಡಬಹುದು.',
    'Nagadali' : 'ನಾಗದಲಿಯನ್ನು ಸಾಮಾನ್ಯವಾಗಿ ಮೂಲಿಕೆ-ಆಫ್-ಗ್ರೇಸ್ ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ, ಇದು ಅಲಂಕಾರಿಕ ಸಸ್ಯ ಮತ್ತು ಮೂಲಿಕೆಯಾಗಿ ಬೆಳೆದ ರೂಟಾದ ಜಾತಿಯಾಗಿದೆ. ಇದು ಬಾಲ್ಕನ್ ಪೆನಿನ್ಸುಲಾಕ್ಕೆ ಸ್ಥಳೀಯವಾಗಿದೆ. ಇದನ್ನು ಈಗ ಪ್ರಪಂಚದಾದ್ಯಂತ ಉದ್ಯಾನಗಳಲ್ಲಿ ಬೆಳೆಯಲಾಗುತ್ತದೆ, ವಿಶೇಷವಾಗಿ ಅದರ ನೀಲಿ ಎಲೆಗಳಿಗಾಗಿ, ಮತ್ತು ಕೆಲವೊಮ್ಮೆ ಬಿಸಿ ಮತ್ತು ಒಣ ಮಣ್ಣಿನ ಪರಿಸ್ಥಿತಿಗಳ ಸಹಿಷ್ಣುತೆಗಾಗಿ. ಇದನ್ನು ಔಷಧೀಯ ಮೂಲಿಕೆಯಾಗಿ, ಕಾಂಡಿಮೆಂಟ್ ಆಗಿ ಮತ್ತು ಸ್ವಲ್ಪ ಮಟ್ಟಿಗೆ ಕೀಟ ನಿವಾರಕವಾಗಿಯೂ ಬೆಳೆಸಲಾಗುತ್ತದೆ. ರೂ ಪಾಕಶಾಲೆಯ ಬಳಕೆಯನ್ನು ಹೊಂದಿದೆ, ಆದರೆ ಇದು ಕಹಿ ಮತ್ತು ಗ್ಯಾಸ್ಟ್ರಿಕ್ ಅಸ್ವಸ್ಥತೆಯನ್ನು ಕೆಲವು ವ್ಯಕ್ತಿಗಳು ಅನುಭವಿಸಬಹುದು, ಇದನ್ನು ಮಿತವಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ. ಹಿಂದಿನ ಕಾಲದಲ್ಲಿ ಹೆಚ್ಚು ವ್ಯಾಪಕವಾಗಿ ಬಳಸಲಾಗಿದ್ದರೂ, ಇದು ಆಧುನಿಕ ಪಾಕಪದ್ಧತಿಯಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಕಂಡುಬರುವ ಮೂಲಿಕೆ ಅಲ್ಲ. ಇಂದು ಇದು ಸಾರ್ವಜನಿಕರಿಗೆ ಮತ್ತು ಹೆಚ್ಚಿನ ಬಾಣಸಿಗರಿಗೆ ಹೆಚ್ಚಾಗಿ ತಿಳಿದಿಲ್ಲ ಮತ್ತು ಕಿರಾಣಿ ಅಂಗಡಿಗಳಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ. ಇದು ಇಥಿಯೋಪಿಯನ್ ಮಸಾಲೆ ಮಿಶ್ರಣವಾದ ಬೆರ್ಬೆರ್‌ನ ಒಂದು ಅಂಶವಾಗಿದೆ ಮತ್ತು ಇಥಿಯೋಪಿಯನ್ ಪಾಕಪದ್ಧತಿಯಲ್ಲಿ ಕಂಡುಬರುತ್ತದೆ. ಇಥಿಯೋಪಿಯಾದಲ್ಲಿ, ತಾಜಾ ರೂ ಅನ್ನು ಕುಡಿಯುವ ಮೊದಲು ಕಾಫಿಯಲ್ಲಿ ಮುಳುಗಿಸಲಾಗುತ್ತದೆ. ಪುರಾತನ ಸಮೀಪದ ಪೂರ್ವ ಮತ್ತು ರೋಮನ್ ಪಾಕಪದ್ಧತಿಯಲ್ಲಿ ಇದನ್ನು ವ್ಯಾಪಕವಾಗಿ ಬಳಸಲಾಗುತ್ತಿತ್ತು (ಇಬ್ನ್ ಸಯ್ಯರ್ ಅಲ್-ವಾರ್ರಾಕ್ ಮತ್ತು ಅಪಿಸಿಯಸ್ ಪ್ರಕಾರ). ರೂ ಅನ್ನು ಗ್ರೀಸ್ ಮತ್ತು ಇತರ ಮೆಡಿಟರೇನಿಯನ್ ದೇಶಗಳಲ್ಲಿ ಸಾಂಪ್ರದಾಯಿಕ ಸುವಾಸನೆಯಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ.',
    'Neem' : 'ಬೇವಿನ ಎಲೆಗಳು ನಂಜುನಿರೋಧಕ ಗುಣವನ್ನು ಹೊಂದಿದ್ದು, ಅದಕ್ಕಾಗಿಯೇ ಇದನ್ನು ಗಾಯಗಳನ್ನು ಗುಣಪಡಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ. ಶ್ಯಾಂಪೂಗಳು ಮತ್ತು ಕಂಡಿಷನರ್‌ಗಳಲ್ಲಿ ಬೇವನ್ನು ವ್ಯಾಪಕವಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ. ಅಜಾಡಿರಾಕ್ಟಾ ಇಂಡಿಕಾವು ಆಂಟಿಫಂಗಲ್ ಮತ್ತು ಬ್ಯಾಕ್ಟೀರಿಯಾ ವಿರೋಧಿ ಗುಣಗಳನ್ನು ಹೊಂದಿದೆ, ಇದು ತಲೆಹೊಟ್ಟು ತೊಡೆದುಹಾಕಲು ಮತ್ತು ನಿಮ್ಮ ಕೂದಲನ್ನು ಬಲಪಡಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಬೇವಿನ ಮರದ ಬಹುತೇಕ ಎಲ್ಲಾ ಭಾಗಗಳು ಉಪಯುಕ್ತವಾಗಿವೆ ಮತ್ತು ಅದರ ಅನೇಕ ಔಷಧೀಯ ಮತ್ತು ಸೌಂದರ್ಯವರ್ಧಕ ಬಳಕೆಗಳು ಅದರ ಬ್ಯಾಕ್ಟೀರಿಯಾ ಮತ್ತು ಆಂಟಿಫಂಗಲ್ ಗುಣಲಕ್ಷಣಗಳನ್ನು ಆಧರಿಸಿವೆ. ಬೇವನ್ನು ಸಾಮಾನ್ಯವಾಗಿ ತಲೆಹೊಟ್ಟು ಚಿಕಿತ್ಸೆಗಾಗಿ ಶ್ಯಾಂಪೂಗಳಲ್ಲಿ ಮತ್ತು ಮೊಡವೆ , ಸೋರಿಯಾಸಿಸ್ ಮತ್ತು ಕ್ರೀಡಾಪಟುವಿನ ಪಾದದಂತಹ ಚರ್ಮದ ಸ್ಥಿತಿಗಳಿಗೆ ಸೋಪ್ ಅಥವಾ ಕ್ರೀಮ್‌ಗಳಲ್ಲಿ ಬಳಸಲಾಗುತ್ತದೆ . ವಿಶೇಷವಾಗಿ ಭಾರತೀಯ ಉಪಖಂಡದಲ್ಲಿ ಕೆಲವು ಟೂತ್‌ಪೇಸ್ಟ್‌ಗಳು ಮತ್ತು ಮೌತ್‌ವಾಶ್‌ಗಳಲ್ಲಿ ಇದು ಒಂದು ಅಂಶವಾಗಿದೆ ಮತ್ತು ಗ್ರಾಮೀಣ ಪ್ರದೇಶಗಳಲ್ಲಿ ಎಳೆಯ ಕೊಂಬೆಗಳನ್ನು ನೇರವಾಗಿ ಕಚ್ಚಾ ಹಲ್ಲುಜ್ಜುವ ಬ್ರಷ್‌ಗಳಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ. ಬೇವಿನ ಎಲೆಗಳನ್ನು ಮಧುಮೇಹಕ್ಕೆ ಸಾಂಪ್ರದಾಯಿಕ ಚಿಕಿತ್ಸೆಯಾಗಿ ದೀರ್ಘಕಾಲ ಬಳಸಲಾಗುತ್ತಿದೆ ಮತ್ತು ಇದು ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆ ಮಟ್ಟವನ್ನು ನಿಯಂತ್ರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ ಎಂದು ಸೂಚಿಸುವ ಕೆಲವು ವೈದ್ಯಕೀಯ ಪುರಾವೆಗಳಿವೆ.ಬೇವಿನ ಎಣ್ಣೆ ಮತ್ತು ಬೇವಿನ ತೊಗಟೆ ಮತ್ತು ಎಲೆಗಳು ಗರ್ಭಿಣಿಯರು ಸೇವಿಸಲು ಅಸುರಕ್ಷಿತವಾಗಿರುತ್ತವೆ ಮತ್ತು ಗರ್ಭಪಾತಕ್ಕೆ ಕಾರಣವಾಗಬಹುದು .',
    'Nithyapushpa' : 'ಮನೆಯಂಗಳದಲ್ಲಿ ಮನಸೂರೆಗೊಳ್ಳುವಂತೆ ಅರಳಿಕೊಳ್ಳುವ ಪುಟ್ಟ ಗಿಡ ನಿತ್ಯ ಪುಷ್ಪ ಅಥವಾ ಸದಾ ಪುಷ್ಪ. ದೇವರ ಪೂಜೆಗೆಂದು ಬಳಸುವ ಈ ಗಿಡದ ಹೂವು ಆರೋಗ್ಯವನ್ನು ವೃದ್ಧಿಸಲು ಕೂಡ ಅಷ್ಟೇ ಮಹತ್ವವನ್ನು ಪಡೆದುಕೊಂಡಿದೆ. ತಿಳಿ ಗುಲಾಬಿ, ಬಿಳಿಯ ಬಣ್ಣದಲ್ಲಿ ಅರಳುವ ಈ ಹೂವು ಅನೇಕ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳಿಗೆ ಪರಿಹಾರ ನೀಡುತ್ತದೆ. ಕ್ಯಾನ್ಸರ್‌ ರೋಗಕ್ಕೆ ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ ಔಷಧವಿಲ್ಲ. ಆದರೆ ಅದನ್ನು ಹಲವು ರೀತಿಯ ಮೂಲಿಕೆ ಹಾಗೂ ಆಹಾರ, ಜೀವನಶೈಲಿಯಿಂದ ನಿಯಂತ್ರಣದಲ್ಲಿಟ್ಟುಕೊಳ್ಳಬಹುದು. ಇದಕ್ಕೆ ನಿತ್ಯ ಪುಷ್ಪ ಉಪಯುಕ್ತವಾಗಿದೆ. ಕ್ಯಾನ್ಸರ್‌ ಜೀವಕೋಶಗಳ ವಿರುದ್ಧ ಹೋರಾಡಲು ನಿತ್ಯ ಪುಷ್ಪದ ಬೇರನ್ನು ಬಳಕೆ ಮಾಡಲಾಗುತ್ತದೆ. ಮಧುಮೇಹ ತಡೆಗೆ ಸಾಕಷ್ಟು ಬಗೆಯ ಮದ್ದುಗಳಿದ್ದರೂ ನಿತ್ಯ ಪುಷ್ಪದ ಬಳಕೆ ಹೆಚ್ಚು ಪರಿಣಾಮಕಾರಿಯಾಗಿದೆ. ಜೀರ್ಣಶಕ್ತಿ ಕಡಿಮೆಯಾದಂತೆ ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆಯ ಮಟ್ಟವು ಹೆಚ್ಚಾಗಲು ಪ್ರಾರಂಭಿಸುತ್ತದೆ. ಆಯುರ್ವೇದವು ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆಯ ಸ್ಪೈಕ್ ಅನ್ನು ನಿಯಂತ್ರಿಸಲು ನಿತ್ಯ ಪುಷ್ಪವನ್ನು ಬಳಸಲು ಶಿಫಾರಸು ಮಾಡುತ್ತದೆ. ಬದಲಾದ ಜೀವನಶೈಲಿ, ಒತ್ತಡದ ಬದುಕು, ಆಹಾರ ಪದ್ಧತಿಯಿಂದ ಅಧಿಕ ರಕ್ತದೊತ್ತಡ ಇತ್ತೀಚಿನ ದಿನಗಳಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಕಾಣಿಸಿಕೊಳ್ಳುವ ಸಮಸ್ಯೆಯಾಗಿದೆ. ಇದಕ್ಕೆ ಧ್ಯಾನ, ಯೋಗದಲ್ಲಿಯೂ ಪರಿಹಾರವಿದೆ. ಅದೇ ರೀತಿ ನಿತ್ಯ ಪುಷ್ಪ ಗಿಡವೂ ಕೂಡ ನಿಮ್ಮ ಅಧಿಕ ರಕ್ತದೊತ್ತಡವನ್ನು ನಿಯಂತ್ರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ.',
    'Nooni' : 'ಏಷ್ಯಾ, ಆಸ್ಟ್ರೇಲಿಯಾ ಮತ್ತು ಪಾಲಿನೇಷ್ಯಾದ ದ್ವೀಪಗಳಿಗೆ ಸ್ಥಳೀಯವಾಗಿರುವ ನೋನಿ ಸಸ್ಯವು ಸಣ್ಣ, ಪೊದೆಸಸ್ಯ ಮರವಾಗಿದೆ. ಸಸ್ಯದ ಬಿಳಿ ಹೂವುಗಳು ಕೊಳವೆಯಾಕಾರದವು. ಹಣ್ಣು ಹಳದಿ-ಹಸಿರು-ಬಿಳಿ ಬಣ್ಣ ಮತ್ತು ದೊಡ್ಡದಾಗಿದ್ದು, ಬೆಣಚುಕಲ್ಲು ಮೇಲ್ಮೈಯನ್ನು ಹೊಂದಿರುತ್ತದೆ. ಮಾಗಿದ ಹಣ್ಣು ವಿಶಿಷ್ಟವಾದ ಚೀಸ್ ತರಹದ, ಕೆಟ್ಟ ವಾಸನೆಯನ್ನು ಹೊಂದಿರುತ್ತದೆ. ನೋನಿಯನ್ನು ಸಾಂಪ್ರದಾಯಿಕವಾಗಿ ಶೀತಗಳು, ಜ್ವರ, ಮಧುಮೇಹ, ಆತಂಕ ಮತ್ತು ಅಧಿಕ ರಕ್ತದೊತ್ತಡಕ್ಕೆ ಬಳಸಲಾಗುತ್ತದೆ, ಜೊತೆಗೆ ಖಿನ್ನತೆ ಮತ್ತು ಆತಂಕಕ್ಕೆ ಬಳಸಲಾಗುತ್ತದೆ. ಸಮೋವನ್ ಸಂಸ್ಕೃತಿಯಲ್ಲಿ ಎಲ್ಲಾ ಸಸ್ಯದ ಭಾಗಗಳನ್ನು ವಿವಿಧ ಕಾಯಿಲೆಗಳಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ, ಮತ್ತು ನೋನಿಯು ಹೆಚ್ಚಾಗಿ ಬಳಸುವ ಹವಾಯಿಯನ್ ಸಸ್ಯ ಔಷಧಿಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ. ಕ್ಲಿನಿಕಲ್ ಪ್ರಯೋಗಗಳಲ್ಲಿ ಸಾಬೀತಾಗದ ಹಕ್ಕುಗಳು ಸೇರಿವೆ: ಬ್ಯಾಕ್ಟೀರಿಯಾದ ಸೋಂಕುಗಳು, ಕೆಮ್ಮು, ಶಿಶುಗಳಲ್ಲಿ ಅತಿಸಾರ ಮತ್ತು ಹೊಟ್ಟೆಯ ಕಾಯಿಲೆಗಳ ಚಿಕಿತ್ಸೆಗಾಗಿ ತೊಗಟೆಯ ಬಳಕೆ; ನೋಯುತ್ತಿರುವ ಅಥವಾ ಕಿರಿಕಿರಿಗೊಂಡ ಕಣ್ಣುಗಳು, ಸ್ಟೈಸ್, ಕಾಂಜಂಕ್ಟಿವಿಟಿಸ್, ಕಣ್ಣಿನ ಉರಿಯೂತ ಮತ್ತು ಕೆಮ್ಮುಗಳಿಗೆ ಹೂವುಗಳು; ಅಸ್ತಮಾ, ಗಾಯಗಳು, ಮುರಿದ ಮೂಳೆಗಳು, ಬಾಯಿ ಮತ್ತು ಗಂಟಲಿನ ಸೋಂಕುಗಳು, ಕ್ಷಯರೋಗ, ಹುಳುಗಳು, ಅತಿಸಾರ, ಜ್ವರ, ವಾಂತಿ, ಕಣ್ಣಿನ ಕಾಯಿಲೆಗಳು, ಸಂಧಿವಾತ, ಖಿನ್ನತೆ, ರೋಗಗ್ರಸ್ತವಾಗುವಿಕೆಗಳು, ಬ್ಯಾಕ್ಟೀರಿಯಾ ಮತ್ತು ಶಿಲೀಂಧ್ರಗಳ ಸೋಂಕುಗಳು, ವೈರಸ್‌ಗಳು ಮತ್ತು ಟಾನಿಕ್‌ಗೆ ಹಣ್ಣು; ಕ್ಯಾನ್ಸರ್ಗೆ ತಾಜಾ ಹಣ್ಣಿನ ರಸ; ಒಣಗಿದ ಎಲೆಗಳನ್ನು ಸೋಂಕುಗಳು, ಸುಟ್ಟಗಾಯಗಳು, ಮಕ್ಕಳ ಎದೆಯ ಶೀತಗಳು ಮತ್ತು ಉರಿಯೂತಗಳಿಗೆ ಬಾಹ್ಯವಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ ಮತ್ತು ಆಂತರಿಕವಾಗಿ ಕುದಿಯುವಿಕೆ, ಪ್ಲೆರೈಸಿ, ಉರಿಯೂತದ ಒಸಡುಗಳು ಮತ್ತು ಸಂಧಿವಾತ ನೋವು; ತಾಜಾ ಎಲೆಗಳನ್ನು ಸುಟ್ಟಗಾಯಗಳಿಗೆ ಬಾಹ್ಯವಾಗಿ ಮತ್ತು ಆಂತರಿಕವಾಗಿ ಜ್ವರ, ರಕ್ತಸ್ರಾವ, ಬ್ಯಾಕ್ಟೀರಿಯಾದ ಸೋಂಕುಗಳು ಮತ್ತು ಉರಿಯೂತಕ್ಕೆ ಬಳಸಲಾಗುತ್ತದೆ; ಮತ್ತು ಬಾಯಿಯ ಹುಣ್ಣುಗಳು, ಜ್ವರಗಳು ಮತ್ತು ಕ್ಯಾನ್ಸರ್ ಊತಗಳಿಗೆ ಬೇರುಗಳು.',
    'Pappaya' : 'ಪರಂಗಿ ಅಥವಾ ಪಪ್ಪಾಯಿ ಹಣ್ಣು ತನ್ನಲ್ಲಿ ಅತಿ ಹೆಚ್ಚು ನೈಸರ್ಗಿಕವಾದ ಸಿಹಿ ಅಂಶವನ್ನು ಒಳಗೊಂಡ ಹಣ್ಣಾಗಿದೆ. ಅಷ್ಟೇ ಪ್ರಮಾಣದ ಆರೋಗ್ಯದ ಲಾಭಗಳನ್ನು ಒಳಗೊಂಡಿರುವ ಪರಂಗಿ ಹಣ್ಣನ್ನು ಮಕ್ಕಳು ದೊಡ್ಡವರು ಮತ್ತು ವಯಸ್ಸಾದವರು ಯಾವುದೇ ಹಿಂಜರಿಕೆಯಿಲ್ಲದೆ ಸೇವನೆ ಮಾಡಬಹುದು. ಹೃದಯದ ಸಮಸ್ಯೆ, ಮುಟ್ಟಿನ ತೊಂದರೆ, ಕಣ್ಣುಗಳ ಆರೋಗ್ಯ ಹೀಗೆ ಅನೇಕ ವಿಧಗಳಲ್ಲಿ ಪರಂಗಿಹಣ್ಣಿನ ಪಾತ್ರ ನಿಮ್ಮ ಆರೋಗ್ಯದ ಮೇಲೆ ಒಳ್ಳೆಯ ಪ್ರಭಾವ ಬೀರುತ್ತದೆ. ಮಾಗಿದ ಪಪ್ಪಾಯಿ ಹಣ್ಣುಗಳನ್ನು ಹಲವಾರು ಬಗೆಗಳಲ್ಲಿ ತಿನ್ನುವುದು ಪರಿಚಿತ. ತಂಪುಪಾನೀಯ, ಜಾಮ್, ಐಸ್‍ಕ್ರೀಮ್, ಸಿರಪ್ ಮುಂತಾದವುಗಳಲ್ಲೂ ಇದನ್ನು ಬಳಸುವುದಿದೆ. ಕಾಯಿಯನ್ನು ತರಕಾರಿಯಾಗಿ ಉಪಯೋಗಿಸಬಹುದು. ಇದು ಉತ್ತಮ ಜೀರ್ಣಕಾರಿ ಎಂದು ಪ್ರಸಿದ್ಧವಾಗಿದೆ. ಇದಕ್ಕೆ ಕಾರಣ ಇದರಲ್ಲಿರುವ ಪಪೇಯಿನ್ ಎಂಬ ಕಿಣ್ವ. ಹಣ್ಣುಗಳಿಗಿಂತ ಕಾಯಿಗಳಲ್ಲಿ ಹೆಚ್ಚು ಮೊತ್ತದಲ್ಲಿರುವ ಈ ಕಿಣ್ವ ಕಾಯಿಗಳ ಹಾಲ್ನೊರೆಯಲ್ಲಿ ವಿಪುಲವಾಗಿದೆ. ಇದೊಂದು ಪ್ರೊಟೀನ್ ವಿಶ್ಲೇಷಕ ಕಿಣ್ವ. ಪೆಪ್ಸಿನ್ ಕಿಣ್ವದಂತೆ ಕಾರ್ಯ ನಿರ್ವಹಿಸುತ್ತದೆ. ಇದನ್ನು ಮಾಂಸ ಮೃದುಗೊಳಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ. ಚೂಯಿಂಗ್ ಗಮ್, ಅಲಂಕರಣ ಸಾಮಗ್ರಿಗಳು, ಚರ್ಮ ಹದಗಾರಿಕೆ, ಜೀರ್ಣಕಾರಿ ಔಷಧಿ ತಯಾರಿಕೆ, ಸ್ವಾಭಾವಿಕ ರೇಷ್ಮೆಯ ಅಂಟುಪದಾರ್ಥವನ್ನು ತೆಗೆಯುವುದಕ್ಕೆ ಇದನ್ನು ಉಪಯೋಗಿಸುವುದುಂಟು. ',
    'Pepper' : 'ಕರಿಮೆಣಸು ( ಪೈಪರ್ ನಿಗ್ರಮ್ ) ಪೈಪೆರೇಸಿ ಕುಟುಂಬದಲ್ಲಿ ಹೂಬಿಡುವ ಬಳ್ಳಿಯಾಗಿದ್ದು , ಅದರ ಹಣ್ಣುಗಳಿಗೆ ( ಮೆಣಸಿನಕಾಯಿ ) ಬೆಳೆಸಲಾಗುತ್ತದೆ, ಇದನ್ನು ಸಾಮಾನ್ಯವಾಗಿ ಒಣಗಿಸಿ ಮಸಾಲೆ ಮತ್ತು ಮಸಾಲೆಯಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ . ಹಣ್ಣು ಡ್ರೂಪ್ (ಸ್ಟೋನ್‌ಫ್ರೂಟ್) ಆಗಿದ್ದು, ಇದು ಸುಮಾರು 5 ಮಿಮೀ (0.20 ಇಂಚು) ವ್ಯಾಸದಲ್ಲಿದೆ (ತಾಜಾ ಮತ್ತು ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರಬುದ್ಧ), ಕಡು ಕೆಂಪು, ಮತ್ತು ಒಂದು ಕಾಳುಮೆಣಸಿನ ಬೀಜವನ್ನು ಸುತ್ತುವರೆದಿರುವ ಕಲ್ಲನ್ನು ಹೊಂದಿರುತ್ತದೆ . ಮೆಣಸಿನಕಾಯಿಗಳು ಮತ್ತು ಅವುಗಳಿಂದ ಪಡೆದ ನೆಲದ ಮೆಣಸನ್ನು ಮೆಣಸು ಎಂದು ವಿವರಿಸಬಹುದು ಅಥವಾ ಹೆಚ್ಚು ನಿಖರವಾಗಿ ಕರಿಮೆಣಸು (ಬೇಯಿಸಿದ ಮತ್ತು ಒಣಗಿದ ಬಲಿಯದ ಹಣ್ಣು), ಹಸಿರು ಮೆಣಸು (ಒಣಗಿದ ಬಲಿಯದ ಹಣ್ಣು), ಅಥವಾ ಬಿಳಿ ಮೆಣಸು (ಮಾಗಿದ ಹಣ್ಣಿನ ಬೀಜಗಳು). ಮೆಣಸಿನಕಾಳುಗಳಿಂದ ಒಂದು ರೀತಿಯ ಚಂಚಲತೈಲವನ್ನೂ ಪಡೆಯಬಹುದಾಗಿದ್ದು ಇದನ್ನು ವಿವಿಧ ರೀತಿಯ ಆಹಾರವಸ್ತುಗಳಿಗೆ ಮತ್ತು ಪಾನೀಯಗಳಿಗೆ ರುಚಿ ಒದಗಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ. ಕೇರಳದ ಕೆಲವಡೆ ಹಸುರುಮೆಣಸನ್ನೂ ಉಪ್ಪಿನಕಾಯಿಯ ರೂಪದಲ್ಲಿ ಬಳಸುವುದಿದೆ.',
    'Pomegranate' : 'ದಾಳಿಂಬೆಯು ಲಿತ್ರೇಸಿ ಕುಟುಂಬಕ್ಕೆ ಸೇರಿದೆ.ಇದು ಮೂಲತಃ ಪರ್ಷಿಯಾ ದೇಶದ ಮೂಲ ನಿವಾಸಿ. ರುಚಿಕರವಾದ ಹಣ್ಣಿಗೆ ಪ್ರಸಿದ್ಧವಾಗಿದೆ. ದಾಳಿಂಬೆಯು ಮಧ್ಯ ಪೂರ್ವ, ದಕ್ಷಿಣ ಏಷ್ಯಾ, ಮತ್ತು ಮೆಡಿಟರೇನಿಯನ್ ಈ ಪ್ರದೇಶದುದ್ದಕ್ಕೂ ಬೆಳೆಯುತ್ತವೆ, ಮತ್ತು ಕ್ಯಾಲಿಫೋರ್ನಿಯಾ ಮತ್ತು ಅರಿಜೋನದ ಒಣ ಹವಾಮಾನಗಳಲ್ಲಿ ಕೂಡ ಬೆಳೆಯುತ್ತವೆ. ಇದರ ಹಣ್ಣು ರುಚಿಕರವಾಗಿದ್ದು,ತಿನ್ನಲು ಹಾಗೂ ಪಾನೀಯ ತಯಾರಿಸಲು ಉಪಯೋಗಿಸುತ್ತಾರೆ. ಹಣ್ಣಿನ ಸಿಪ್ಪೆ,ತೊಗಟೆ,ಬೀಜ ಹಾಗೂ ಎಲೆಗಳು ಔಷಧಿಗಳಲ್ಲಿ ಬಳಸಲ್ಪಡುತ್ತವೆ. ದಾರುವು ಸಣ್ಣ ಕಣರಜನೆ ಹೊಂದಿದ್ದು,ಕೈ ಬೆತ್ತ,ಉಪಕರಣಗಳ ಹಿಡಿ ಇತ್ಯಾದಿಗಳ ತಯಾರಿಕೆಯಲ್ಲಿ ಉಪಯೋಗಿಸಲ್ಪಡುತ್ತದೆ. ಪ್ರತಿದಿನ ದಾಳಿಂಬೆ ಸೇವಿಸಿದರೆ, ಇದರಲ್ಲಿರುವ ವಿಟಮಿನ್ ಸಿ, ಆಂಟಿ ಆಕ್ಸಿಡೆಂಟ್ ಮತ್ತು ಉರಿಯೂತದ ಮತ್ತು ಆಂಟಿವೈರಲ್ ಗುಣಗಳು ಅನೇಕ ರೋಗಗಳಿಂದ ರಕ್ಷಿಸುತ್ತದೆ. ತಜ್ಞರ ಪ್ರಕಾರ, ದಾಳಿಂಬೆಯ ಔಷಧೀಯ ಗುಣಗಳಿಂದಾಗಿ, ಇದು ಅಪಾಯಕಾರಿ ರೋಗಗಳು ಬರದಂತೆ ತಡೆಯಬಲ್ಲದು. ದಾಳಿಂಬೆ ನಮ್ಮ ದೇಹವನ್ನು ಆರೋಗ್ಯವಾಗಿರಿಸುವುದಲ್ಲದೆ, ನಮ್ಮ ಕೂದಲು ಮತ್ತು ಚರ್ಮವನ್ನು ಸಹ ಆರೋಗ್ಯವಾಗಿರಿಸುತ್ತದೆ.',
    'Raktachandini' : ' ರಕ್ತಚಂದನ ದಕ್ಷಿಣ ಭಾರತದ ಪರ್ವತ ವ್ಯಾಪ್ತಿಯ ಸ್ಥಳೀಯ ಸಸ್ಯ. ಕೆಂಪು ಸ್ಯಾಂಡಲ್‍ವುಡ್, ಕೆಂಪು ಚಂದನ, ಇವು ಈ ಮರಕ್ಕಿರುವ ಸಾಮಾನ್ಯ ಹೆಸರುಗಳು. ಇದು ಫ್ಯಾಬೇಸೀ ಕುಟುಂಬದ ಫ್ಯಾಬಾಯ್ಡೀ ಉಪಕುಟುಂಬಕ್ಕೆ ಸೇರಿರುವ ಪರ್ಣಪಾತಿ ಮರ (ರೆಡ್ ಸ್ಯಾಂಡರ್ಸ್). ರಕ್ತಚಂದನದಿಂದ ತಯಾರಿಸಲ್ಪಟ್ಟ ವಸ್ತುಗಳು ಹಾಗೂ ಪೀಠೋಪಕರಣಗಳಿಗೆ ಬಹಳಷ್ಟು ಬೇಡಿಕೆಯಿದ್ದು, ದುಬಾರಿಯಾಗಿದೆ. ರಕ್ತಚಂದನದ ಚೌಬೀನೆ ಭಾರವಾದ್ದೂ (ಘನ ಅಡಿಗೆ 76 ಪೌಂ) ಗಡುಸಾದ್ದೂ ಬಾಳಿಕೆ ಬರುವಂಥದ್ದೂ ಆಗಿದೆ. ಹದಮಾಡುವುದೂ ಸುಲಭ. ಹೊರ ಮರ ಮಾಸಲು ಬಿಳಿಯ ಬಣ್ಣಕ್ಕಿದ್ದರೆ ಚೇಗುಮರ ಕುಯ್ದ ಹೊಸದರಲ್ಲಿ ಕೆಂಪು ಬಣ್ಣದ್ದಾಗಿದ್ದು ಕ್ರಮೇಣ ಕಂದುಬಣ್ಣಕ್ಕೆ ತಿರುಗುತ್ತದೆ. ಚೌಬೀನೆ ಕೆತ್ತನೆ ಕೆಲಸಗಳಿಗೆ ಉಪಯುಕ್ತ. ರಕ್ತಚಂದನದ ಬೊಂಬೆಗಳು ಪ್ರಸಿದ್ಧವಾಗಿವೆ. ರಕ್ತಚಂದನದ ಕಾಷ್ಠದಲ್ಲಿ ಸ್ಯಾಂಟಲಿನ್ ಎಂಬ ಕೆಂಪು ವರ್ಣಕವೂ ಡೀಸಾಕ್ಸಿ ಸ್ಯಾಂಟಲಿನ್ ಎಂಬ ಹಳದಿ ವರ್ಣಕವೂ ಇವೆ. ಉಣ್ಣೆ, ಹತ್ತಿಬಟ್ಟೆ, ಚರ್ಮ ಮತ್ತು ಬೇರೆ ತೆರನ ಚೌಬೀನೆಗಳಿಗು ಕೆಲವೊಂದು ಆಹಾರ ಪದಾರ್ಥಗಳು, ಔಷಧಿಗಳು ಹಾಗೂ ಕಾಗದ ಪಲ್ಪಿಗೂ ಬಣ್ಣಕಟ್ಟಲು ಈ ವರ್ಣಕಗಳನ್ನು ಬಳಸಲಾಗುತ್ತದೆ. ಮರಕ್ಕೆ ಪ್ರತಿಬಂಧಕ, ಉತ್ತೇಜಕಗುಣಗಳೂ ಇವೆ. ಊತ, ತಲೆನೋವು ನಿವಾರಣೆಗೆ ಇದರ ಲೇಪ ಹಚ್ಚಲಾಗುತ್ತದೆ.',
    'Rose' : 'ಹೂವುಗಳ ರಾಣಿ ಎಂದೇ ಕರೆಸಿಕೊಂಡಿರುವ ಗುಲಾಬಿ ನೋಡಲು ಮಾತ್ರ ಸುಂದರ ಎನ್ನುವಂತಿಲ್ಲ. ಅದು ಸಮೃದ್ಧವಾದ ಔಷಧೀಯ ಗುಣಗಳನ್ನು ತನ್ನಲ್ಲಡಗಿಸಿಕೊಂಡಿದೆ. ಗುಲಾಬಿಯ ಸುವಾಸನೆ ಅಮಲನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ. ಗುಲಾಬಿಯ ಎಸಳನ್ನು ರಾತ್ರಿ ನೀರಿನಲ್ಲಿ ನೆನೆಸಿಟ್ಟು, ಬೆಳಗಾದಾಗ ಆ ನೀರಿನಿಂದ ಕಣ್ಣುಗಳನ್ನು ತೊಳೆದರೆ, ಕಣ್ಣಿನ ಉರಿ ಮಾಯವಾಗುತ್ತದೆ. ಒಣಗಿದ ರೇಖುಗಳನ್ನು ಜೇನುತುಪ್ಪದೊಂದಿಗೆ ಕಲಸಿ ಸೇವಿಸುವುದರಿಂದ ಉದರಬೇನೆ ಗುಣವಾಗುತ್ತದೆ. ದೇಹದ ಉಷ್ಣತೆ ತಗ್ಗುತ್ತದೆ. ವೀಳ್ಯದೆಲೆಯೊಡನೆ ಗುಲಾಬಿಯ ರೇಖುಗಳನ್ನು ಸೇರಿಸಿ ತಿಂದರೆ ಬಾಯಿಯ ದುರ್ಗಂಧ ನೀಗುತ್ತದೆ. ಒಂದು ಹಿಡಿಯಷ್ಟು ಗುಲಾಬಿ ಮೊಗ್ಗನ್ನು ಅರೆದು, ಮೊಸರಿನಲ್ಲಿ ಕಲಸಿ ಸೇವಿಸಿದರೆ ಶೀತಬಾಧೆ ನೀಗುತ್ತದೆ. ಗುಲಾಬಿಯ ಎಸಳುಗಳನ್ನು ಮಡಿಕೆಯಲ್ಲಿ ಹಾಕಿ, ನೀರಿನಲ್ಲಿ ಕುದಿಸಿ, ಬೆಳಗ್ಗೆ ಮತ್ತು ರಾತ್ರಿ ಸಕ್ಕರೆ ಬೆರೆಸಿ ಕುಡಿದರೆ ಮಲಬದ್ಧತೆ ನೀಗುತ್ತದೆ. ಮೂಲ ರೋಗದ ಕಾವು ತಗ್ಗುತ್ತದೆ.',
    'Sapota' : 'ಸಪೋತಗೆ ವಿವಿಧ ರೀತಿಯ ಹೆಸರುಗಳು ಕೂಡ ಇದೆ. ಇದನ್ನು ಚಿಕ್ಕ, ಚಿಕ್ಕೂ, ಲಮೂತ್, ಸಪೊಡಿಲ್ಲಾ, ನೋಸ್ ಬೆರ್ರಿ ಮತ್ತು ಸಪೋಟಿ ಇತ್ಯಾದಿ ಹೆಸರುಗಳಿಂದ ಕರೆಯುತ್ತಾರೆ. ಭಾರತದಲ್ಲಿ ಸಪೋಟ ಹಣ್ಣನ್ನು ಹೆಚ್ಚಾಗಿ ಕರ್ನಾಟಕ, ಗುಜರಾತ್, ಮಹಾರಾಷ್ಟ್ರ, ಪಶ್ಚಿಮ ಬಂಗಾಳ, ಆಂಧ್ರ ಪ್ರದೇಶ ಮತ್ತು ತಮಿಳುನಾಡಿನಲ್ಲಿ ಬೆಳೆಯುತ್ತಾರೆ. ಸಪೋತ ಹಣ್ಣಿನ ಜ್ಯೂಸ್, ಜಾಮ್, ಸ್ಮೂಥಿ, ಸಿಹಿ ತಿಂಡಿಗಳು ಇತ್ಯಾದಿಗಳನ್ನು ತಯಾರಿಸುವರು. 100 ಗ್ರಾಂ ಸಪೋಟ ದಲ್ಲಿ 83 ಕ್ಯಾಲರಿ ಇದೆ. ಆಹಾರದ ನಾರಿನಾಂಶವನ್ನು ಹೊಂದಿರುವಂತಹ ಇದು ವಿರೇಚಕ ಗುಣವನ್ನು ಹೊಂದಿದೆ. ಈ ಹಣ್ಣಿನಲ್ಲಿ ವಿಟಮಿನ್ ಸಿ, ಎ, ನಿಯಾಸಿನ್, ಫಾಲಟೆ ಮತ್ತು ಖನಿಜಾಂಶ ಗಳಾಗಿರುವಂತಹ ಕಬ್ಬಿನಾಂಶ, ಪೊಟಾಶಿಯಂ ಮತ್ತು ತಾಮ್ರವಿದೆ. ಆಂಟಿಆಕ್ಸಿಡೆಂಟ್, ಉರಿಯೂತ ಶಮನಕಾರಿ, ವೈರಲ್ ವಿರೋಧಿ, ಬ್ಯಾಕ್ಟೀರಿಯಾ ವಿರೋಧಿ ಮತ್ತು ನಂಜುನಿರೋಧಕ ಗುಣಗಳು ಕೂಡ ಇದರಲ್ಲಿ ಇದೆ. ಸಪೋಟ ಹಣ್ಣಿನಲ್ಲಿ ಸಸ್ಯಜನ್ಯವಾಗಿರುವಂತಹ ಪಾಲಿಪೆನಾಲ್ ಇದ್ದು, ಹೊಟ್ಟೆಯಲ್ಲಿ ಇದು ಆಮ್ಲದ ಸ್ರವಿಸುವಿಕೆಯನ್ನು ತಟಸ್ಥಗೊಳಿಸುವುದು. ಪರಾವಲಂಬಿ ವಿರೋಧಿ, ವೈರಲ್ ವಿರೋಧಿ, ಉರಿಯೂತ ಶಮನಕಾರಿ ಮತ್ತು ಬ್ಯಾಕ್ಟೀರಿಯಾ ವಿರೋಧಿ ಗುಣ ಹೊಂದಿರುವಂತಹ ಸಪೋತ ಹಣ್ಣು ಕಿರಿಕಿರಿ ಉಂಟು ಮಾಡುವ ಹೊಟ್ಟೆಗೆ ಶಮನ ನೀಡುವುದು.',
    'Tulasi' : 'ತುಳಸಿಯನ್ನು ಲಕ್ಷ್ಮಿ ದೇವಿಯ ಸಂಕೇತವೆಂದು ಪರಿಗಣಿಸಲಾಗಿದೆ. ಮನೆಯ ಅಂಗಳದಲ್ಲಿ ತುಳಸಿಯನ್ನು ಇಡುವುದು ಅತ್ಯಂತ ಮಂಗಳಕರವೆಂದು ಪರಿಗಣಿಸಲಾಗಿದೆ. ಯಾವ ಮನೆಯಲ್ಲಿ ತುಳಸಿ ಇರುತ್ತದೆಯೋ ಆ ಮನೆಯಲ್ಲಿ ಸದಾಕಾಲ ಸುಖ - ಸಮೃದ್ಧಿ ನೆಲೆಸಿರುತ್ತದೆ ಎನ್ನುವ ನಂಬಿಕೆಯಿದೆ. ಒಣಗಿದ ತುಳಸಿ ಎಲೆಗಳಿಂದ ಸ್ನಾನ ಮಾಡುವುದರಿಂದ ದೇಹದಲ್ಲಿ ನಕಾರಾತ್ಮಕ ಶಕ್ತಿ ನೆಲೆಸುವುದಿಲ್ಲ. ತುಳಸಿ ಉರಿಯೂತವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಮತ್ತು ನೋವನ್ನು ನಿವಾರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.  ತುಳಸಿ ವಾಕರಿಕೆ ಮತ್ತು ವಾಂತಿಯನ್ನು ತಡೆಯಲು ಮತ್ತು ನಿವಾರಿಸಲು ಸಹಾಯ ಮಾಡುವ ಆಂಟಿಮೆಟಿಕ್ ಗುಣಗಳನ್ನು ಹೊಂದಿದೆ. ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆ ಮಟ್ಟವನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ ಎಂದು ತೋರಿಸಲಾಗಿದೆ, ಇದು ಮಧುಮೇಹ ಹೊಂದಿರುವ ವ್ಯಕ್ತಿಗಳಿಗೆ ಪ್ರಯೋಜನಕಾರಿಯಾಗಿದೆ. ಆಸ್ತಮಾ ರೋಗಲಕ್ಷಣಗಳನ್ನು ನಿವಾರಿಸಲು ಮತ್ತು ಉಸಿರಾಟದ ಆರೋಗ್ಯವನ್ನು ಉತ್ತೇಜಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ತುಳಸಿ ಒತ್ತಡವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಮತ್ತು ವಿಶ್ರಾಂತಿಯನ್ನು ಉತ್ತೇಜಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    'Wood_sorel' : 'ವುಡ್ ಸೋರ್ರೆಲ್, ಆಕ್ಸಾಲಿಸ್ (ಕುಟುಂಬ ಆಕ್ಸಾಲಿಡೇಸಿ) ಕುಲದ ಹಲವಾರು ಹೂಬಿಡುವ ಸಸ್ಯ. ಯುರೋಪ್ ಮತ್ತು ಏಷ್ಯಾದ ಭಾಗಗಳ ಸಾಮಾನ್ಯ ಮರದ ಸೋರ್ರೆಲ್ (ಆಕ್ಸಾಲಿಸ್ ಅಸಿಟೋಸೆಲ್ಲಾ). ಯುರೋಪ್ ಮತ್ತು ಏಷ್ಯಾದ ಕೆಲವು ಭಾಗಗಳ ಸಾಮಾನ್ಯ ಮರದ ಸೋರ್ರೆಲ್ (O. ಅಸಿಟೋಸೆಲ್ಲಾ) ಒಂದು ಸಣ್ಣ ಕಾಂಡವಿಲ್ಲದ ಸಸ್ಯವಾಗಿದ್ದು, ಕ್ಲೋವರ್ ತರಹದ ಮೂರು-ಭಾಗದ ಎಲೆಗಳು ತೆವಳುವ ಚಿಪ್ಪುಗಳುಳ್ಳ ಬೇರುಕಾಂಡದಿಂದ ಉದ್ಭವಿಸುತ್ತವೆ. ಉಭಯಲಿಂಗಿ ಹೂವುಗಳು ಎಲೆಯ ಅಕ್ಷದಿಂದ ಹುಟ್ಟುವ ಕಾಂಡದ ಮೇಲೆ ಏಕಾಂಗಿಯಾಗಿ ಹುಟ್ಟುತ್ತವೆ. ಹೂವುಗಳು ಐದು ನೇರಳೆ-ಸಿರೆಗಳ ಬಿಳಿ ದಳಗಳನ್ನು ಹೊಂದಿರುತ್ತವೆ. ಹಣ್ಣು ಒಂದು ಕ್ಯಾಪ್ಸುಲ್ ಆಗಿದೆ. ಬೀಜಗಳು ತಿರುಳಿರುವ ಕೋಟ್ ಅನ್ನು ಹೊಂದಿರುತ್ತವೆ, ಅದು ಸ್ಥಿತಿಸ್ಥಾಪಕವಾಗಿ ಹಿಂದಕ್ಕೆ ಸುರುಳಿಯಾಗುತ್ತದೆ, ನಿಜವಾದ ಬೀಜವನ್ನು ಹೊರಹಾಕುತ್ತದೆ. ಚಿಗುರೆಲೆಗಳು, ಕುಲದ ಇತರ ಜಾತಿಗಳಂತೆ, ಹಿಂದಕ್ಕೆ ಮಡಚಿಕೊಳ್ಳುತ್ತವೆ ಮತ್ತು ರಾತ್ರಿಯಲ್ಲಿ ಕುಸಿಯುತ್ತವೆ. ಉತ್ತರ ಅಮೆರಿಕಾದಲ್ಲಿ ಈ ಹೆಸರನ್ನು ಮುಖ್ಯವಾಗಿ ಮೌಂಟೇನ್ ವುಡ್ ಸೋರ್ರೆಲ್ (O. ಮೊಂಟಾನಾ) ಗಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ, ಇದು ಕಾಂಡವಿಲ್ಲದ ಟ್ರಿಫೊಲಿಯೇಟ್ (ಅಂದರೆ, ಮೂರು ಚಿಗುರೆಲೆಗಳೊಂದಿಗೆ) ಮೂಲಿಕೆ ದಕ್ಷಿಣ ಕೆನಡಾದಿಂದ ದಕ್ಷಿಣಕ್ಕೆ ಟೆನ್ನೆಸ್ಸೀ ಮತ್ತು ಪಶ್ಚಿಮಕ್ಕೆ ಮಿನ್ನೇಸೋಟದವರೆಗೆ. ಇದು ಸುಮಾರು 15 ಸೆಂ.ಮೀ (6 ಇಂಚು) ಎತ್ತರಕ್ಕೆ ಬೆಳೆಯುತ್ತದೆ ಮತ್ತು ಗುಲಾಬಿ ಬಣ್ಣದ ಕಾಂಡಗಳು ಮತ್ತು ಮೇ ನಿಂದ ಆಗಸ್ಟ್ ವರೆಗೆ ಕಾಣಿಸಿಕೊಳ್ಳುವ ಬಿಳಿ ಅಥವಾ ಕೆಂಪು ಬಣ್ಣದ ಹೂವುಗಳನ್ನು ಹೊಂದಿರುತ್ತದೆ. ವುಡ್ ಸೋರೆಲ್ ಎಂಬ ಹೆಸರನ್ನು ಕೆಲವೊಮ್ಮೆ ಪಾಲಿಗೊನೇಸಿ ಕುಟುಂಬದ ಕುರಿ ಸೋರೆಲ್ (ರುಮೆಕ್ಸ್ ಅಸಿಟೋಸೆಲ್ಲಾ) ಮತ್ತು ಬೆಗೊನಿಯಾಸಿ ಕುಟುಂಬದ ವೆಸ್ಟ್ ಇಂಡಿಯನ್ ಬಿಗೋನಿಯಾ, ಬೆಗೊನಿಯಾ ಅಕ್ಯುಟಿಫೋಲಿಯಾಕ್ಕೆ ತಪ್ಪಾಗಿ ಅನ್ವಯಿಸಲಾಗುತ್ತದೆ.'
    # Add more Kannada descriptions here
}

# Configure upload folder
UPLOAD_FOLDER = 'static/uploads'
TTS_FOLDER = 'static/tts'
TTS1_FOLDER = 'static/tts1'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['TTS_FOLDER'] = TTS_FOLDER
app.config['TTS1_FOLDER'] = TTS1_FOLDER

# Ensure folders exist
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(TTS_FOLDER, exist_ok=True)
os.makedirs(TTS1_FOLDER, exist_ok=True)

def preprocess_image(image_path):
    """Preprocess the uploaded image for prediction."""
    img = tf.keras.preprocessing.image.load_img(image_path, target_size=(299, 299))
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
    return img_array

def generate_tts_english(text, filename):
    """Generate English TTS audio."""
    tts = gTTS(text=text, lang='en')
    file_path = os.path.join(app.config['TTS1_FOLDER'], filename)
    tts.save(file_path)
    return file_path

def generate_tts_kannada(text, filename):
    """Generate Kannada TTS audio."""
    tts = gTTS(text=text, lang='kn')
    file_path = os.path.join(app.config['TTS_FOLDER'], filename)
    tts.save(file_path)
    return file_path
CONFIDENCE_THRESHOLD = 60  # Set your threshold (in percentage)

@app.route('/', methods=['GET', 'POST'])
def index():
    """Render the home page and handle image upload."""
    if request.method == 'POST':
        if 'image' not in request.files or request.files['image'].filename == '':
            return render_template('index.html', error="Please upload a valid image.")
        
        file = request.files['image']
        if file:
            file_path = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
            file.save(file_path)

            # Predict
            img_array = preprocess_image(file_path)
            predictions = model.predict(img_array)
            predicted_index = np.argmax(predictions)
            predicted_label = labels.get(predicted_index, "Unknown")
            confidence = 100 * np.max(predictions)

            # Check if confidence meets the threshold
            if confidence < CONFIDENCE_THRESHOLD:
                return render_template(
                    'result.html',
                    label="Unknown Plant",
                    confidence=confidence,
                    description="Unable to identify the plant with high confidence.",
                    information="Please try again with a clearer image or different plant.",
                    audio_path=None,
                    audio1_path=None,
                    image_path=url_for('static', filename=f'uploads/{file.filename}')
                )

            # Get plant information and TTS
            plant_information = plant_desc.get(predicted_label, "This information is not available.")
            tts1_file = generate_tts_english(plant_information, f"{predicted_label}.mp3")
            
            plant_description = plant_info.get(predicted_label, "ಈ ಗಿಡದ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ.")
            tts_file = generate_tts_kannada(plant_description, f"{predicted_label}.mp3")
            
            # Pass data to result page
            return render_template(
                'result.html',
                label=predicted_label,
                confidence=confidence,
                description=plant_description,
                information=plant_information,
                audio_path=url_for('static', filename=f'tts1/{predicted_label}.mp3'),
                audio1_path=url_for('static', filename=f'tts/{predicted_label}.mp3'),
                image_path=url_for('static', filename=f'uploads/{file.filename}')
            )

    return render_template('index.html')


if __name__ == '__main__':
    app.run(debug=True)



